#region License

/*
 * All content copyright Marko Lahma, unless otherwise indicated. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 */

#endregion

namespace Quartz.Examples.Example06;

/// <summary>
/// A job that fails in a way it cannot recover from, and takes its own triggers down with it.
/// </summary>
/// <author>Bill Kratzer</author>
/// <author>Marko Lahma (.NET)</author>
[PersistJobDataAfterExecution]
[DisallowConcurrentExecution]
public class BadJob2 : IJob
{
    /// <summary>
    /// Called by the <see cref="IScheduler" /> when a <see cref="ITrigger" />
    /// fires that is associated with the <see cref="IJob" />.
    /// </summary>
    /// <param name="context">Execution context.</param>
    /// <param name="cancellationToken">The cancellation instruction.</param>
    public virtual ValueTask Execute(IJobExecutionContext context, CancellationToken cancellationToken = default)
    {
        JobKey jobKey = context.JobDetail.Key;
        Console.WriteLine($"---{jobKey} fired at {context.FireTimeUtc.LocalDateTime:HH:mm:ss}");

        // a contrived example of an exception that
        // will be generated by this job due to a
        // divide by zero error
        try
        {
            int zero = 0;
            int calculation = 4815 / zero;
        }
        catch (Exception e)
        {
            Console.WriteLine("--- Error in job!");

            // Quartz will unschedule every trigger associated with this job, so this is the last time
            // it runs. Watch badJob2 stop while badJob1 carries on.
            throw new JobExecutionException(e) { UnscheduleAllTriggers = true };
        }

        Console.WriteLine($"---{jobKey} completed");
        return default;
    }
}
