//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

namespace Quartz.Xml.JobSchedulingData10
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://quartznet.sourceforge.net/JobSchedulingData")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://quartznet.sourceforge.net/JobSchedulingData",
        IsNullable = false, ElementName = "quartz")]
    public partial class QuartzXmlConfiguration10
    {
        private joblistenerType[] joblistenerField;

        private triggerlistenerType[] triggerlistenerField;

        private calendarType[] calendarField;

        private jobType[] jobField;

        private string versionField;

        private bool overwriteexistingjobsField;

        public QuartzXmlConfiguration10()
        {
            this.overwriteexistingjobsField = true;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("job-listener")]
        public joblistenerType[] joblistener
        {
            get { return this.joblistenerField; }
            set { this.joblistenerField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("trigger-listener")]
        public triggerlistenerType[] triggerlistener
        {
            get { return this.triggerlistenerField; }
            set { this.triggerlistenerField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("calendar")]
        public calendarType[] calendar
        {
            get { return this.calendarField; }
            set { this.calendarField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("job")]
        public jobType[] job
        {
            get { return this.jobField; }
            set { this.jobField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get { return this.versionField; }
            set { this.versionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("overwrite-existing-jobs")]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool overwriteexistingjobs
        {
            get { return this.overwriteexistingjobsField; }
            set { this.overwriteexistingjobsField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "job-listenerType",
        Namespace = "http://quartznet.sourceforge.net/JobSchedulingData")]
    public partial class joblistenerType
    {
        private string typeField;

        private string nameField;

        public joblistenerType()
        {
            this.nameField = "required";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get { return this.typeField; }
            set { this.typeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("required")]
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof (cronType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof (simpleType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://quartznet.sourceforge.net/JobSchedulingData")]
    public abstract partial class abstractTriggerType
    {
        private string nameField;

        private string groupField;

        private string descriptionField;

        private string misfireinstructionField;

        private string calendarnameField;

        private bool volatileField;

        private bool volatileFieldSpecified;

        private string triggerlistenerrefField;

        private jobdatamapType jobdatamapField;

        public abstractTriggerType()
        {
            this.volatileField = false;
        }

        /// <remarks/>
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <remarks/>
        public string group
        {
            get { return this.groupField; }
            set { this.groupField = value; }
        }

        /// <remarks/>
        public string description
        {
            get { return this.descriptionField; }
            set { this.descriptionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("misfire-instruction")]
        public string misfireinstruction
        {
            get { return this.misfireinstructionField; }
            set { this.misfireinstructionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("calendar-name")]
        public string calendarname
        {
            get { return this.calendarnameField; }
            set { this.calendarnameField = value; }
        }

        /// <remarks/>
        public bool @volatile
        {
            get { return this.volatileField; }
            set { this.volatileField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool volatileSpecified
        {
            get { return this.volatileFieldSpecified; }
            set { this.volatileFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("trigger-listener-ref")]
        public string triggerlistenerref
        {
            get { return this.triggerlistenerrefField; }
            set { this.triggerlistenerrefField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("job-data-map")]
        public jobdatamapType jobdatamap
        {
            get { return this.jobdatamapField; }
            set { this.jobdatamapField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "job-data-mapType",
        Namespace = "http://quartznet.sourceforge.net/JobSchedulingData")]
    public partial class jobdatamapType
    {
        private entryType[] entryField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entry")]
        public entryType[] entry
        {
            get { return this.entryField; }
            set { this.entryField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://quartznet.sourceforge.net/JobSchedulingData")]
    public partial class entryType
    {
        private string keyField;

        private string valueField;

        /// <remarks/>
        public string key
        {
            get { return this.keyField; }
            set { this.keyField = value; }
        }

        /// <remarks/>
        public string value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://quartznet.sourceforge.net/JobSchedulingData")]
    public partial class cronType : abstractTriggerType
    {
        private string jobnameField;

        private string jobgroupField;

        private System.DateTime starttimeField;

        private System.DateTime endtimeField;

        private string cronexpressionField;

        private string timezoneField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("job-name")]
        public string jobname
        {
            get { return this.jobnameField; }
            set { this.jobnameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("job-group")]
        public string jobgroup
        {
            get { return this.jobgroupField; }
            set { this.jobgroupField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("start-time")]
        public System.DateTime starttime
        {
            get { return this.starttimeField; }
            set { this.starttimeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("end-time")]
        public System.DateTime endtime
        {
            get { return this.endtimeField; }
            set { this.endtimeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cron-expression")]
        public string cronexpression
        {
            get { return this.cronexpressionField; }
            set { this.cronexpressionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("time-zone")]
        public string timezone
        {
            get { return this.timezoneField; }
            set { this.timezoneField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://quartznet.sourceforge.net/JobSchedulingData")]
    public partial class simpleType : abstractTriggerType
    {
        private string jobnameField;

        private string jobgroupField;

        private System.DateTime starttimeField;

        private System.DateTime endtimeField;

        private bool endtimeFieldSpecified;

        private string repeatcountField;

        private string repeatintervalField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("job-name")]
        public string jobname
        {
            get { return this.jobnameField; }
            set { this.jobnameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("job-group")]
        public string jobgroup
        {
            get { return this.jobgroupField; }
            set { this.jobgroupField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("start-time")]
        public System.DateTime starttime
        {
            get { return this.starttimeField; }
            set { this.starttimeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("end-time")]
        public System.DateTime endtime
        {
            get { return this.endtimeField; }
            set { this.endtimeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endtimeSpecified
        {
            get { return this.endtimeFieldSpecified; }
            set { this.endtimeFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("repeat-count", DataType = "integer")]
        public string repeatcount
        {
            get { return this.repeatcountField; }
            set { this.repeatcountField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("repeat-interval", DataType = "nonNegativeInteger")]
        public string repeatinterval
        {
            get { return this.repeatintervalField; }
            set { this.repeatintervalField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://quartznet.sourceforge.net/JobSchedulingData")]
    public partial class triggerType
    {
        private abstractTriggerType itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cron", typeof (cronType))]
        [System.Xml.Serialization.XmlElementAttribute("simple", typeof (simpleType))]
        public abstractTriggerType Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "job-detailType",
        Namespace = "http://quartznet.sourceforge.net/JobSchedulingData")]
    public partial class jobdetailType
    {
        private string nameField;

        private string groupField;

        private string descriptionField;

        private string jobtypeField;

        private string joblistenerrefField;

        private bool volatileField;

        private bool durableField;

        private bool recoverField;

        private jobdatamapType jobdatamapField;

        public jobdetailType()
        {
            this.volatileField = false;
            this.durableField = false;
            this.recoverField = false;
        }

        /// <remarks/>
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <remarks/>
        public string group
        {
            get { return this.groupField; }
            set { this.groupField = value; }
        }

        /// <remarks/>
        public string description
        {
            get { return this.descriptionField; }
            set { this.descriptionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("job-type")]
        public string jobtype
        {
            get { return this.jobtypeField; }
            set { this.jobtypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("job-listener-ref")]
        public string joblistenerref
        {
            get { return this.joblistenerrefField; }
            set { this.joblistenerrefField = value; }
        }

        /// <remarks/>
        public bool @volatile
        {
            get { return this.volatileField; }
            set { this.volatileField = value; }
        }

        /// <remarks/>
        public bool durable
        {
            get { return this.durableField; }
            set { this.durableField = value; }
        }

        /// <remarks/>
        public bool recover
        {
            get { return this.recoverField; }
            set { this.recoverField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("job-data-map")]
        public jobdatamapType jobdatamap
        {
            get { return this.jobdatamapField; }
            set { this.jobdatamapField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://quartznet.sourceforge.net/JobSchedulingData")]
    public partial class jobType
    {
        private jobdetailType jobdetailField;

        private triggerType[] triggerField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("job-detail")]
        public jobdetailType jobdetail
        {
            get { return this.jobdetailField; }
            set { this.jobdetailField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("trigger")]
        public triggerType[] trigger
        {
            get { return this.triggerField; }
            set { this.triggerField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://quartznet.sourceforge.net/JobSchedulingData")]
    public partial class calendarType
    {
        private string nameField;

        private string descriptionField;

        private calendarType basecalendarField;

        private string typeField;

        private bool replaceField;

        public calendarType()
        {
            this.replaceField = false;
        }

        /// <remarks/>
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <remarks/>
        public string description
        {
            get { return this.descriptionField; }
            set { this.descriptionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("base-calendar")]
        public calendarType basecalendar
        {
            get { return this.basecalendarField; }
            set { this.basecalendarField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get { return this.typeField; }
            set { this.typeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool replace
        {
            get { return this.replaceField; }
            set { this.replaceField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "trigger-listenerType",
        Namespace = "http://quartznet.sourceforge.net/JobSchedulingData")]
    public partial class triggerlistenerType
    {
        private string typeField;

        private string nameField;

        public triggerlistenerType()
        {
            this.nameField = "required";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get { return this.typeField; }
            set { this.typeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("required")]
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }
    }
}
