--
-- Quartz.NET schema -- Oracle
--
-- GENERATED FILE. Describe the schema in build/Build.DatabaseSchema.cs and run
-- 'dotnet fallout GenerateSchema'; edits made here are overwritten.
--
-- This is what AdoJobStore runs for itself when SchemaProvisioning.CreateIfMissing is
-- configured. It is not the script to run by hand -- use
-- database/tables/tables_oracle.sql for that, which is written for a person with a
-- database client and drops an existing schema before it recreates one.
--
-- Every statement creates only what is missing, and nothing here ever drops anything.
-- So it is safe to run against a schema that already exists, and safe to run twice.
--
-- '{0}' is the configured table prefix and '{1}' is the same prefix with any schema
-- qualifier removed, for the identifiers that cannot carry one -- index, constraint and
-- catalog-lookup names. They are substituted at runtime, so a schema provisioned under a
-- prefix of its own collides with nothing.
--
-- Statements are separated by a line reading exactly '--;;'. The job store splits on
-- it and sends each piece to the provider as one command, which is why no dialect's batch
-- separator appears: no GO, no lone '/', no SET TERM.
--
--;;
-- {0}JOB_DETAILS
DECLARE
  table_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO table_exists FROM user_tables
  WHERE table_name = UPPER('{1}JOB_DETAILS');
  IF table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE {0}JOB_DETAILS (SCHED_NAME VARCHAR2(120) NOT NULL, JOB_NAME VARCHAR2(200) NOT NULL, JOB_GROUP VARCHAR2(200) NOT NULL, DESCRIPTION VARCHAR2(250) NULL, JOB_CLASS_NAME VARCHAR2(250) NOT NULL, IS_DURABLE VARCHAR2(1) NOT NULL, IS_NONCONCURRENT VARCHAR2(1) NOT NULL, IS_UPDATE_DATA VARCHAR2(1) NOT NULL, REQUESTS_RECOVERY VARCHAR2(1) NOT NULL, JOB_DATA BLOB NULL, CONSTRAINT {1}JOB_DETAILS_PK PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP))';
  END IF;
END;
--;;
-- {0}TRIGGERS
DECLARE
  table_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO table_exists FROM user_tables
  WHERE table_name = UPPER('{1}TRIGGERS');
  IF table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE {0}TRIGGERS (SCHED_NAME VARCHAR2(120) NOT NULL, TRIGGER_NAME VARCHAR2(200) NOT NULL, TRIGGER_GROUP VARCHAR2(200) NOT NULL, JOB_NAME VARCHAR2(200) NOT NULL, JOB_GROUP VARCHAR2(200) NOT NULL, DESCRIPTION VARCHAR2(250) NULL, NEXT_FIRE_TIME NUMBER(19) NULL, PREV_FIRE_TIME NUMBER(19) NULL, PRIORITY NUMBER(13) NULL, TRIGGER_STATE VARCHAR2(16) NOT NULL, TRIGGER_TYPE VARCHAR2(8) NOT NULL, START_TIME NUMBER(19) NOT NULL, END_TIME NUMBER(19) NULL, CALENDAR_NAME VARCHAR2(200) NULL, MISFIRE_INSTR NUMBER(2) NULL, MISFIRE_ORIG_FIRE_TIME NUMBER(19) NULL, EXECUTION_GROUP VARCHAR2(200) NULL, PREFERRED_NODE VARCHAR2(200) NULL, PREFERRED_NODE_AUTO VARCHAR2(1) DEFAULT ''0'' NOT NULL, RETRY_POLICY VARCHAR2(250) NULL, RETRY_ATTEMPT NUMBER(13) NULL, JOB_DATA BLOB NULL, CONSTRAINT {1}TRIGGERS_PK PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP), CONSTRAINT {1}TRIGGER_TO_JOBS_FK FOREIGN KEY (SCHED_NAME,JOB_NAME,JOB_GROUP) REFERENCES {0}JOB_DETAILS (SCHED_NAME,JOB_NAME,JOB_GROUP))';
  END IF;
END;
--;;
-- {0}SIMPLE_TRIGGERS
DECLARE
  table_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO table_exists FROM user_tables
  WHERE table_name = UPPER('{1}SIMPLE_TRIGGERS');
  IF table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE {0}SIMPLE_TRIGGERS (SCHED_NAME VARCHAR2(120) NOT NULL, TRIGGER_NAME VARCHAR2(200) NOT NULL, TRIGGER_GROUP VARCHAR2(200) NOT NULL, REPEAT_COUNT NUMBER(7) NOT NULL, REPEAT_INTERVAL NUMBER(12) NOT NULL, TIMES_TRIGGERED NUMBER(10) NOT NULL, CONSTRAINT {1}SIMPLE_TRIG_PK PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP), CONSTRAINT {1}SIMPLE_TRIG_TO_TRIG_FK FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) REFERENCES {0}TRIGGERS (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP))';
  END IF;
END;
--;;
-- {0}CRON_TRIGGERS
DECLARE
  table_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO table_exists FROM user_tables
  WHERE table_name = UPPER('{1}CRON_TRIGGERS');
  IF table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE {0}CRON_TRIGGERS (SCHED_NAME VARCHAR2(120) NOT NULL, TRIGGER_NAME VARCHAR2(200) NOT NULL, TRIGGER_GROUP VARCHAR2(200) NOT NULL, CRON_EXPRESSION VARCHAR2(120) NOT NULL, TIME_ZONE_ID VARCHAR2(80), CONSTRAINT {1}CRON_TRIG_PK PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP), CONSTRAINT {1}CRON_TRIG_TO_TRIG_FK FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) REFERENCES {0}TRIGGERS (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP))';
  END IF;
END;
--;;
-- {0}SIMPROP_TRIGGERS
DECLARE
  table_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO table_exists FROM user_tables
  WHERE table_name = UPPER('{1}SIMPROP_TRIGGERS');
  IF table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE {0}SIMPROP_TRIGGERS (SCHED_NAME VARCHAR2(120) NOT NULL, TRIGGER_NAME VARCHAR2(200) NOT NULL, TRIGGER_GROUP VARCHAR2(200) NOT NULL, STR_PROP_1 VARCHAR2(512) NULL, STR_PROP_2 VARCHAR2(512) NULL, STR_PROP_3 VARCHAR2(512) NULL, INT_PROP_1 NUMBER(10) NULL, INT_PROP_2 NUMBER(10) NULL, LONG_PROP_1 NUMBER(19) NULL, LONG_PROP_2 NUMBER(19) NULL, DEC_PROP_1 NUMERIC(13,4) NULL, DEC_PROP_2 NUMERIC(13,4) NULL, BOOL_PROP_1 VARCHAR2(1) NULL, BOOL_PROP_2 VARCHAR2(1) NULL, TIME_ZONE_ID VARCHAR2(80) NULL, CONSTRAINT {1}SIMPROP_TRIG_PK PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP), CONSTRAINT {1}SIMPROP_TRIG_TO_TRIG_FK FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) REFERENCES {0}TRIGGERS (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP))';
  END IF;
END;
--;;
-- {0}BLOB_TRIGGERS
DECLARE
  table_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO table_exists FROM user_tables
  WHERE table_name = UPPER('{1}BLOB_TRIGGERS');
  IF table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE {0}BLOB_TRIGGERS (SCHED_NAME VARCHAR2(120) NOT NULL, TRIGGER_NAME VARCHAR2(200) NOT NULL, TRIGGER_GROUP VARCHAR2(200) NOT NULL, BLOB_DATA BLOB NULL, CONSTRAINT {1}BLOB_TRIG_PK PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP), CONSTRAINT {1}BLOB_TRIG_TO_TRIG_FK FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) REFERENCES {0}TRIGGERS (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP))';
  END IF;
END;
--;;
-- {0}CALENDARS
DECLARE
  table_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO table_exists FROM user_tables
  WHERE table_name = UPPER('{1}CALENDARS');
  IF table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE {0}CALENDARS (SCHED_NAME VARCHAR2(120) NOT NULL, CALENDAR_NAME VARCHAR2(200) NOT NULL, CALENDAR BLOB NOT NULL, CONSTRAINT {1}CALENDARS_PK PRIMARY KEY (SCHED_NAME,CALENDAR_NAME))';
  END IF;
END;
--;;
-- {0}PAUSED_TRIGGER_GRPS
DECLARE
  table_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO table_exists FROM user_tables
  WHERE table_name = UPPER('{1}PAUSED_TRIGGER_GRPS');
  IF table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE {0}PAUSED_TRIGGER_GRPS (SCHED_NAME VARCHAR2(120) NOT NULL, TRIGGER_GROUP VARCHAR2(200) NOT NULL, CONSTRAINT {1}PAUSED_TRIG_GRPS_PK PRIMARY KEY (SCHED_NAME,TRIGGER_GROUP))';
  END IF;
END;
--;;
-- {0}PAUSED_JOB_GRPS
DECLARE
  table_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO table_exists FROM user_tables
  WHERE table_name = UPPER('{1}PAUSED_JOB_GRPS');
  IF table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE {0}PAUSED_JOB_GRPS (SCHED_NAME VARCHAR2(120) NOT NULL, JOB_GROUP VARCHAR2(200) NOT NULL, CONSTRAINT {1}PAUSED_JOB_GRPS_PK PRIMARY KEY (SCHED_NAME,JOB_GROUP))';
  END IF;
END;
--;;
-- {0}FIRED_TRIGGERS
DECLARE
  table_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO table_exists FROM user_tables
  WHERE table_name = UPPER('{1}FIRED_TRIGGERS');
  IF table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE {0}FIRED_TRIGGERS (SCHED_NAME VARCHAR2(120) NOT NULL, ENTRY_ID VARCHAR2(140) NOT NULL, TRIGGER_NAME VARCHAR2(200) NOT NULL, TRIGGER_GROUP VARCHAR2(200) NOT NULL, INSTANCE_NAME VARCHAR2(200) NOT NULL, FIRED_TIME NUMBER(19) NOT NULL, SCHED_TIME NUMBER(19) NOT NULL, PRIORITY NUMBER(13) NOT NULL, STATE VARCHAR2(16) NOT NULL, JOB_NAME VARCHAR2(200) NULL, JOB_GROUP VARCHAR2(200) NULL, IS_NONCONCURRENT VARCHAR2(1) NULL, REQUESTS_RECOVERY VARCHAR2(1) NULL, EXECUTION_GROUP VARCHAR2(200) NULL, CONSTRAINT {1}FIRED_TRIGGER_PK PRIMARY KEY (SCHED_NAME,ENTRY_ID))';
  END IF;
END;
--;;
-- {0}SCHEDULER_STATE
DECLARE
  table_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO table_exists FROM user_tables
  WHERE table_name = UPPER('{1}SCHEDULER_STATE');
  IF table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE {0}SCHEDULER_STATE (SCHED_NAME VARCHAR2(120) NOT NULL, INSTANCE_NAME VARCHAR2(200) NOT NULL, LAST_CHECKIN_TIME NUMBER(19) NOT NULL, CHECKIN_INTERVAL NUMBER(13) NOT NULL, CONSTRAINT {1}SCHEDULER_STATE_PK PRIMARY KEY (SCHED_NAME,INSTANCE_NAME))';
  END IF;
END;
--;;
-- {0}LOCKS
DECLARE
  table_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO table_exists FROM user_tables
  WHERE table_name = UPPER('{1}LOCKS');
  IF table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE {0}LOCKS (SCHED_NAME VARCHAR2(120) NOT NULL, LOCK_NAME VARCHAR2(40) NOT NULL, CONSTRAINT {1}LOCKS_PK PRIMARY KEY (SCHED_NAME,LOCK_NAME))';
  END IF;
END;
--;;
-- IDX_{1}J_G_N
DECLARE
  index_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO index_exists FROM user_indexes WHERE index_name = UPPER('IDX_{1}J_G_N');
  IF index_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_{1}J_G_N ON {0}JOB_DETAILS(SCHED_NAME,JOB_GROUP,JOB_NAME)';
  END IF;
END;
--;;
-- IDX_{1}T_J
DECLARE
  index_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO index_exists FROM user_indexes WHERE index_name = UPPER('IDX_{1}T_J');
  IF index_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_{1}T_J ON {0}TRIGGERS(SCHED_NAME,JOB_NAME,JOB_GROUP)';
  END IF;
END;
--;;
-- IDX_{1}T_G_N
DECLARE
  index_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO index_exists FROM user_indexes WHERE index_name = UPPER('IDX_{1}T_G_N');
  IF index_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_{1}T_G_N ON {0}TRIGGERS(SCHED_NAME,TRIGGER_GROUP,TRIGGER_NAME)';
  END IF;
END;
--;;
-- IDX_{1}T_C
DECLARE
  index_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO index_exists FROM user_indexes WHERE index_name = UPPER('IDX_{1}T_C');
  IF index_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_{1}T_C ON {0}TRIGGERS(SCHED_NAME,CALENDAR_NAME)';
  END IF;
END;
--;;
-- IDX_{1}T_NFT_ST
DECLARE
  index_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO index_exists FROM user_indexes WHERE index_name = UPPER('IDX_{1}T_NFT_ST');
  IF index_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_{1}T_NFT_ST ON {0}TRIGGERS(SCHED_NAME,TRIGGER_STATE,NEXT_FIRE_TIME)';
  END IF;
END;
--;;
-- IDX_{1}T_NFT_ST_MISFIRE
DECLARE
  index_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO index_exists FROM user_indexes WHERE index_name = UPPER('IDX_{1}T_NFT_ST_MISFIRE');
  IF index_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_{1}T_NFT_ST_MISFIRE ON {0}TRIGGERS(SCHED_NAME,MISFIRE_INSTR,NEXT_FIRE_TIME,TRIGGER_STATE)';
  END IF;
END;
--;;
-- IDX_{1}FT_INST_JOB_REQ_RCVRY
DECLARE
  index_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO index_exists FROM user_indexes WHERE index_name = UPPER('IDX_{1}FT_INST_JOB_REQ_RCVRY');
  IF index_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_{1}FT_INST_JOB_REQ_RCVRY ON {0}FIRED_TRIGGERS(SCHED_NAME,INSTANCE_NAME,REQUESTS_RECOVERY)';
  END IF;
END;
--;;
-- IDX_{1}FT_J_G
DECLARE
  index_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO index_exists FROM user_indexes WHERE index_name = UPPER('IDX_{1}FT_J_G');
  IF index_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_{1}FT_J_G ON {0}FIRED_TRIGGERS(SCHED_NAME,JOB_NAME,JOB_GROUP)';
  END IF;
END;
--;;
-- IDX_{1}FT_T_G
DECLARE
  index_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO index_exists FROM user_indexes WHERE index_name = UPPER('IDX_{1}FT_T_G');
  IF index_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_{1}FT_T_G ON {0}FIRED_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)';
  END IF;
END;
