--
-- Quartz.NET schema -- Firebird
--
-- GENERATED FILE. Describe the schema in build/Build.DatabaseSchema.cs and run
-- 'dotnet fallout GenerateSchema'; edits made here are overwritten.
--
-- This is what AdoJobStore runs for itself when SchemaProvisioning.CreateIfMissing is
-- configured. It is not the script to run by hand -- use
-- database/tables/tables_firebird.sql for that, which is written for a person with a
-- database client and drops an existing schema before it recreates one.
--
-- Every statement creates only what is missing, and nothing here ever drops anything.
-- So it is safe to run against a schema that already exists, and safe to run twice.
--
-- '{0}' is the configured table prefix and '{1}' is the same prefix with any schema
-- qualifier removed, for the identifiers that cannot carry one -- index, constraint and
-- catalog-lookup names. They are substituted at runtime, so a schema provisioned under a
-- prefix of its own collides with nothing.
--
-- Statements are separated by a line reading exactly '--;;'. The job store splits on
-- it and sends each piece to the provider as one command, which is why no dialect's batch
-- separator appears: no GO, no lone '/', no SET TERM.
--
-- Each CREATE runs through EXECUTE STATEMENT ... WITH AUTONOMOUS TRANSACTION, which is
-- the COMMIT the fresh-install script writes between its statements: Firebird has to
-- see a table committed before another table's foreign key can reference it, and the
-- job store runs this whole file inside one transaction of its own.
--
--;;
-- {0}JOB_DETAILS
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATIONS
                 WHERE TRIM(RDB$RELATION_NAME) = UPPER('{1}JOB_DETAILS'))) THEN
    EXECUTE STATEMENT 'CREATE TABLE {0}JOB_DETAILS (SCHED_NAME VARCHAR(120) NOT NULL, JOB_NAME VARCHAR(150) NOT NULL, JOB_GROUP VARCHAR(150) NOT NULL, DESCRIPTION VARCHAR(250) DEFAULT NULL, JOB_CLASS_NAME VARCHAR(250) NOT NULL, IS_DURABLE SMALLINT NOT NULL, IS_NONCONCURRENT SMALLINT NOT NULL, IS_UPDATE_DATA SMALLINT NOT NULL, REQUESTS_RECOVERY SMALLINT NOT NULL, JOB_DATA BLOB DEFAULT NULL, CONSTRAINT PK_{1}JOB_DETAILS PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP))'
      WITH AUTONOMOUS TRANSACTION;
END
--;;
-- {0}TRIGGERS
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATIONS
                 WHERE TRIM(RDB$RELATION_NAME) = UPPER('{1}TRIGGERS'))) THEN
    EXECUTE STATEMENT 'CREATE TABLE {0}TRIGGERS (SCHED_NAME VARCHAR(120) NOT NULL, TRIGGER_NAME VARCHAR(150) NOT NULL, TRIGGER_GROUP VARCHAR(150) NOT NULL, JOB_NAME VARCHAR(150) NOT NULL, JOB_GROUP VARCHAR(150) NOT NULL, DESCRIPTION VARCHAR(250) DEFAULT NULL, NEXT_FIRE_TIME BIGINT DEFAULT NULL, PREV_FIRE_TIME BIGINT DEFAULT NULL, PRIORITY INTEGER DEFAULT NULL, TRIGGER_STATE VARCHAR(16) NOT NULL, TRIGGER_TYPE VARCHAR(8) NOT NULL, START_TIME BIGINT NOT NULL, END_TIME BIGINT DEFAULT NULL, CALENDAR_NAME VARCHAR(200) DEFAULT NULL, MISFIRE_INSTR SMALLINT DEFAULT NULL, MISFIRE_ORIG_FIRE_TIME BIGINT DEFAULT NULL, EXECUTION_GROUP VARCHAR(200), PREFERRED_NODE VARCHAR(200), PREFERRED_NODE_AUTO SMALLINT DEFAULT 0 NOT NULL, RETRY_POLICY VARCHAR(250), RETRY_ATTEMPT INTEGER DEFAULT NULL, JOB_DATA BLOB DEFAULT NULL, CONSTRAINT PK_{1}TRIGGERS PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP), CONSTRAINT FK_{1}TRIGGERS_1 FOREIGN KEY (SCHED_NAME,JOB_NAME,JOB_GROUP) REFERENCES {0}JOB_DETAILS (SCHED_NAME,JOB_NAME,JOB_GROUP))'
      WITH AUTONOMOUS TRANSACTION;
END
--;;
-- {0}SIMPLE_TRIGGERS
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATIONS
                 WHERE TRIM(RDB$RELATION_NAME) = UPPER('{1}SIMPLE_TRIGGERS'))) THEN
    EXECUTE STATEMENT 'CREATE TABLE {0}SIMPLE_TRIGGERS (SCHED_NAME VARCHAR(120) NOT NULL, TRIGGER_NAME VARCHAR(150) NOT NULL, TRIGGER_GROUP VARCHAR(150) NOT NULL, REPEAT_COUNT BIGINT NOT NULL, REPEAT_INTERVAL BIGINT NOT NULL, TIMES_TRIGGERED BIGINT NOT NULL, CONSTRAINT PK_{1}SIMPLE_TRIGGERS PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP), CONSTRAINT FK_{1}SIMPLE_TRIGGERS_1 FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) REFERENCES {0}TRIGGERS (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP))'
      WITH AUTONOMOUS TRANSACTION;
END
--;;
-- {0}CRON_TRIGGERS
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATIONS
                 WHERE TRIM(RDB$RELATION_NAME) = UPPER('{1}CRON_TRIGGERS'))) THEN
    EXECUTE STATEMENT 'CREATE TABLE {0}CRON_TRIGGERS (SCHED_NAME VARCHAR(120) NOT NULL, TRIGGER_NAME VARCHAR(150) NOT NULL, TRIGGER_GROUP VARCHAR(150) NOT NULL, CRON_EXPRESSION VARCHAR(250) NOT NULL, TIME_ZONE_ID VARCHAR(80), CONSTRAINT PK_{1}CRON_TRIGGERS PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP), CONSTRAINT FK_{1}CRON_TRIGGERS_1 FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) REFERENCES {0}TRIGGERS (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP))'
      WITH AUTONOMOUS TRANSACTION;
END
--;;
-- {0}SIMPROP_TRIGGERS
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATIONS
                 WHERE TRIM(RDB$RELATION_NAME) = UPPER('{1}SIMPROP_TRIGGERS'))) THEN
    EXECUTE STATEMENT 'CREATE TABLE {0}SIMPROP_TRIGGERS (SCHED_NAME VARCHAR(120) NOT NULL, TRIGGER_NAME VARCHAR(150) NOT NULL, TRIGGER_GROUP VARCHAR(150) NOT NULL, STR_PROP_1 VARCHAR(512) DEFAULT NULL, STR_PROP_2 VARCHAR(512) DEFAULT NULL, STR_PROP_3 VARCHAR(512) DEFAULT NULL, INT_PROP_1 INTEGER DEFAULT NULL, INT_PROP_2 INTEGER DEFAULT NULL, LONG_PROP_1 BIGINT DEFAULT NULL, LONG_PROP_2 BIGINT DEFAULT NULL, DEC_PROP_1 NUMERIC(9,0) DEFAULT NULL, DEC_PROP_2 NUMERIC(9,0) DEFAULT NULL, BOOL_PROP_1 SMALLINT DEFAULT NULL, BOOL_PROP_2 SMALLINT DEFAULT NULL, TIME_ZONE_ID VARCHAR(80) DEFAULT NULL, CONSTRAINT PK_{1}SIMPROP_TRIGGERS PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP), CONSTRAINT FK_{1}SIMPROP_TRIGGERS_1 FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) REFERENCES {0}TRIGGERS (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP))'
      WITH AUTONOMOUS TRANSACTION;
END
--;;
-- {0}BLOB_TRIGGERS
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATIONS
                 WHERE TRIM(RDB$RELATION_NAME) = UPPER('{1}BLOB_TRIGGERS'))) THEN
    EXECUTE STATEMENT 'CREATE TABLE {0}BLOB_TRIGGERS (SCHED_NAME VARCHAR(120) NOT NULL, TRIGGER_NAME VARCHAR(150) NOT NULL, TRIGGER_GROUP VARCHAR(150) NOT NULL, BLOB_DATA BLOB DEFAULT NULL, CONSTRAINT PK_{1}BLOB_TRIGGERS PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP), CONSTRAINT FK_{1}BLOB_TRIGGERS_1 FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) REFERENCES {0}TRIGGERS (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP))'
      WITH AUTONOMOUS TRANSACTION;
END
--;;
-- {0}CALENDARS
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATIONS
                 WHERE TRIM(RDB$RELATION_NAME) = UPPER('{1}CALENDARS'))) THEN
    EXECUTE STATEMENT 'CREATE TABLE {0}CALENDARS (SCHED_NAME VARCHAR(120) NOT NULL, CALENDAR_NAME VARCHAR(200) NOT NULL, CALENDAR BLOB NOT NULL, CONSTRAINT PK_{1}CALENDARS PRIMARY KEY (SCHED_NAME,CALENDAR_NAME))'
      WITH AUTONOMOUS TRANSACTION;
END
--;;
-- {0}PAUSED_TRIGGER_GRPS
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATIONS
                 WHERE TRIM(RDB$RELATION_NAME) = UPPER('{1}PAUSED_TRIGGER_GRPS'))) THEN
    EXECUTE STATEMENT 'CREATE TABLE {0}PAUSED_TRIGGER_GRPS (SCHED_NAME VARCHAR(120) NOT NULL, TRIGGER_GROUP VARCHAR(150) NOT NULL, CONSTRAINT PK_{1}PAUSED_TRIGGER_GRPS PRIMARY KEY (SCHED_NAME,TRIGGER_GROUP))'
      WITH AUTONOMOUS TRANSACTION;
END
--;;
-- {0}PAUSED_JOB_GRPS
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATIONS
                 WHERE TRIM(RDB$RELATION_NAME) = UPPER('{1}PAUSED_JOB_GRPS'))) THEN
    EXECUTE STATEMENT 'CREATE TABLE {0}PAUSED_JOB_GRPS (SCHED_NAME VARCHAR(120) NOT NULL, JOB_GROUP VARCHAR(150) NOT NULL, CONSTRAINT PK_{1}PAUSED_JOB_GRPS PRIMARY KEY (SCHED_NAME,JOB_GROUP))'
      WITH AUTONOMOUS TRANSACTION;
END
--;;
-- {0}FIRED_TRIGGERS
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATIONS
                 WHERE TRIM(RDB$RELATION_NAME) = UPPER('{1}FIRED_TRIGGERS'))) THEN
    EXECUTE STATEMENT 'CREATE TABLE {0}FIRED_TRIGGERS (SCHED_NAME VARCHAR(120) NOT NULL, ENTRY_ID VARCHAR(140) NOT NULL, TRIGGER_NAME VARCHAR(150) NOT NULL, TRIGGER_GROUP VARCHAR(150) NOT NULL, INSTANCE_NAME VARCHAR(200) NOT NULL, FIRED_TIME BIGINT NOT NULL, SCHED_TIME BIGINT NOT NULL, PRIORITY INTEGER NOT NULL, STATE VARCHAR(16) NOT NULL, JOB_NAME VARCHAR(150) DEFAULT NULL, JOB_GROUP VARCHAR(150) DEFAULT NULL, IS_NONCONCURRENT SMALLINT NOT NULL, REQUESTS_RECOVERY SMALLINT DEFAULT NULL, EXECUTION_GROUP VARCHAR(200), CONSTRAINT PK_{1}FIRED_TRIGGERS PRIMARY KEY (SCHED_NAME,ENTRY_ID))'
      WITH AUTONOMOUS TRANSACTION;
END
--;;
-- {0}SCHEDULER_STATE
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATIONS
                 WHERE TRIM(RDB$RELATION_NAME) = UPPER('{1}SCHEDULER_STATE'))) THEN
    EXECUTE STATEMENT 'CREATE TABLE {0}SCHEDULER_STATE (SCHED_NAME VARCHAR(120) NOT NULL, INSTANCE_NAME VARCHAR(200) NOT NULL, LAST_CHECKIN_TIME BIGINT NOT NULL, CHECKIN_INTERVAL BIGINT NOT NULL, CONSTRAINT PK_{1}SCHEDULER_STATE PRIMARY KEY (SCHED_NAME,INSTANCE_NAME))'
      WITH AUTONOMOUS TRANSACTION;
END
--;;
-- {0}LOCKS
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATIONS
                 WHERE TRIM(RDB$RELATION_NAME) = UPPER('{1}LOCKS'))) THEN
    EXECUTE STATEMENT 'CREATE TABLE {0}LOCKS (SCHED_NAME VARCHAR(120) NOT NULL, LOCK_NAME VARCHAR(40) NOT NULL, CONSTRAINT PK_{1}LOCKS PRIMARY KEY (SCHED_NAME,LOCK_NAME))'
      WITH AUTONOMOUS TRANSACTION;
END
--;;
-- IDX_{1}J_G_N
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE TRIM(RDB$INDEX_NAME) = UPPER('IDX_{1}J_G_N'))) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_{1}J_G_N ON {0}JOB_DETAILS(SCHED_NAME,JOB_GROUP,JOB_NAME)'
      WITH AUTONOMOUS TRANSACTION;
END
--;;
-- IDX_{1}T_J
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE TRIM(RDB$INDEX_NAME) = UPPER('IDX_{1}T_J'))) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_{1}T_J ON {0}TRIGGERS(SCHED_NAME,JOB_NAME,JOB_GROUP)'
      WITH AUTONOMOUS TRANSACTION;
END
--;;
-- IDX_{1}T_G_N
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE TRIM(RDB$INDEX_NAME) = UPPER('IDX_{1}T_G_N'))) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_{1}T_G_N ON {0}TRIGGERS(SCHED_NAME,TRIGGER_GROUP,TRIGGER_NAME)'
      WITH AUTONOMOUS TRANSACTION;
END
--;;
-- IDX_{1}T_C
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE TRIM(RDB$INDEX_NAME) = UPPER('IDX_{1}T_C'))) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_{1}T_C ON {0}TRIGGERS(SCHED_NAME,CALENDAR_NAME)'
      WITH AUTONOMOUS TRANSACTION;
END
--;;
-- IDX_{1}T_NFT_ST
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE TRIM(RDB$INDEX_NAME) = UPPER('IDX_{1}T_NFT_ST'))) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_{1}T_NFT_ST ON {0}TRIGGERS(SCHED_NAME,TRIGGER_STATE,NEXT_FIRE_TIME)'
      WITH AUTONOMOUS TRANSACTION;
END
--;;
-- IDX_{1}T_NFT_ST_MISFIRE
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE TRIM(RDB$INDEX_NAME) = UPPER('IDX_{1}T_NFT_ST_MISFIRE'))) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_{1}T_NFT_ST_MISFIRE ON {0}TRIGGERS(SCHED_NAME,MISFIRE_INSTR,NEXT_FIRE_TIME,TRIGGER_STATE)'
      WITH AUTONOMOUS TRANSACTION;
END
--;;
-- IDX_{1}FT_INST_JOB_REQ_RCVRY
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE TRIM(RDB$INDEX_NAME) = UPPER('IDX_{1}FT_INST_JOB_REQ_RCVRY'))) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_{1}FT_INST_JOB_REQ_RCVRY ON {0}FIRED_TRIGGERS(SCHED_NAME,INSTANCE_NAME,REQUESTS_RECOVERY)'
      WITH AUTONOMOUS TRANSACTION;
END
--;;
-- IDX_{1}FT_J_G
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE TRIM(RDB$INDEX_NAME) = UPPER('IDX_{1}FT_J_G'))) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_{1}FT_J_G ON {0}FIRED_TRIGGERS(SCHED_NAME,JOB_NAME,JOB_GROUP)'
      WITH AUTONOMOUS TRANSACTION;
END
--;;
-- IDX_{1}FT_T_G
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE TRIM(RDB$INDEX_NAME) = UPPER('IDX_{1}FT_T_G'))) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_{1}FT_T_G ON {0}FIRED_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)'
      WITH AUTONOMOUS TRANSACTION;
END
