--
-- Quartz.NET schema -- MySQL
--
-- GENERATED FILE. Describe the schema in build/Build.DatabaseSchema.cs and run
-- 'dotnet fallout GenerateSchema'; edits made here are overwritten.
--
-- This is what AdoJobStore runs for itself when SchemaProvisioning.CreateIfMissing is
-- configured. It is not the script to run by hand -- use
-- database/tables/tables_mysql_innodb.sql for that, which is written for a person with a
-- database client and drops an existing schema before it recreates one.
--
-- Every statement creates only what is missing, and nothing here ever drops anything.
-- So it is safe to run against a schema that already exists, and safe to run twice.
--
-- '{0}' is the configured table prefix and '{1}' is the same prefix with any schema
-- qualifier removed, for the identifiers that cannot carry one -- index, constraint and
-- catalog-lookup names. They are substituted at runtime, so a schema provisioned under a
-- prefix of its own collides with nothing.
--
-- Statements are separated by a line reading exactly '--;;'. The job store splits on
-- it and sends each piece to the provider as one command, which is why no dialect's batch
-- separator appears: no GO, no lone '/', no SET TERM.
--
-- The indexes are declared inside CREATE TABLE rather than as statements of their own:
-- MySQL has no CREATE INDEX IF NOT EXISTS, and the guarded form the migration scripts
-- use needs a user variable, which MySqlConnector reads as a parameter placeholder
-- unless the connection string sets AllowUserVariables.
--
--;;
-- {0}JOB_DETAILS
CREATE TABLE IF NOT EXISTS {0}JOB_DETAILS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  JOB_NAME VARCHAR(200) NOT NULL,
  JOB_GROUP VARCHAR(200) NOT NULL,
  DESCRIPTION VARCHAR(250) NULL,
  JOB_CLASS_NAME VARCHAR(250) NOT NULL,
  IS_DURABLE BOOLEAN NOT NULL,
  IS_NONCONCURRENT BOOLEAN NOT NULL,
  IS_UPDATE_DATA BOOLEAN NOT NULL,
  REQUESTS_RECOVERY BOOLEAN NOT NULL,
  JOB_DATA BLOB NULL,
  PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP),
  KEY IDX_{1}J_G_N (SCHED_NAME,JOB_GROUP,JOB_NAME)
) ENGINE=InnoDB;
--;;
-- {0}TRIGGERS
CREATE TABLE IF NOT EXISTS {0}TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR(200) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  JOB_NAME VARCHAR(200) NOT NULL,
  JOB_GROUP VARCHAR(200) NOT NULL,
  DESCRIPTION VARCHAR(250) NULL,
  NEXT_FIRE_TIME BIGINT NULL,
  PREV_FIRE_TIME BIGINT NULL,
  PRIORITY INTEGER NULL,
  TRIGGER_STATE VARCHAR(16) NOT NULL,
  TRIGGER_TYPE VARCHAR(8) NOT NULL,
  START_TIME BIGINT NOT NULL,
  END_TIME BIGINT NULL,
  CALENDAR_NAME VARCHAR(200) NULL,
  MISFIRE_INSTR SMALLINT NULL,
  MISFIRE_ORIG_FIRE_TIME BIGINT NULL,
  EXECUTION_GROUP VARCHAR(200) NULL,
  PREFERRED_NODE VARCHAR(200) NULL,
  PREFERRED_NODE_AUTO BOOLEAN NOT NULL DEFAULT FALSE,
  RETRY_POLICY VARCHAR(250) NULL,
  RETRY_ATTEMPT INTEGER NULL,
  JOB_DATA BLOB NULL,
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME,JOB_NAME,JOB_GROUP) REFERENCES {0}JOB_DETAILS (SCHED_NAME,JOB_NAME,JOB_GROUP),
  KEY IDX_{1}T_J (SCHED_NAME,JOB_NAME,JOB_GROUP),
  KEY IDX_{1}T_G_N (SCHED_NAME,TRIGGER_GROUP,TRIGGER_NAME),
  KEY IDX_{1}T_C (SCHED_NAME,CALENDAR_NAME),
  KEY IDX_{1}T_NFT_ST (SCHED_NAME,TRIGGER_STATE,NEXT_FIRE_TIME ASC,PRIORITY DESC,MISFIRE_INSTR),
  KEY IDX_{1}T_NFT_ST_MISFIRE (SCHED_NAME,MISFIRE_INSTR,NEXT_FIRE_TIME,TRIGGER_STATE)
) ENGINE=InnoDB;
--;;
-- {0}SIMPLE_TRIGGERS
CREATE TABLE IF NOT EXISTS {0}SIMPLE_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR(200) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  REPEAT_COUNT BIGINT NOT NULL,
  REPEAT_INTERVAL BIGINT NOT NULL,
  TIMES_TRIGGERED BIGINT NOT NULL,
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) REFERENCES {0}TRIGGERS (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
) ENGINE=InnoDB;
--;;
-- {0}CRON_TRIGGERS
CREATE TABLE IF NOT EXISTS {0}CRON_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR(200) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  CRON_EXPRESSION VARCHAR(120) NOT NULL,
  TIME_ZONE_ID VARCHAR(80),
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) REFERENCES {0}TRIGGERS (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
) ENGINE=InnoDB;
--;;
-- {0}SIMPROP_TRIGGERS
CREATE TABLE IF NOT EXISTS {0}SIMPROP_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR(200) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  STR_PROP_1 VARCHAR(512) NULL,
  STR_PROP_2 VARCHAR(512) NULL,
  STR_PROP_3 VARCHAR(512) NULL,
  INT_PROP_1 INT NULL,
  INT_PROP_2 INT NULL,
  LONG_PROP_1 BIGINT NULL,
  LONG_PROP_2 BIGINT NULL,
  DEC_PROP_1 NUMERIC(13,4) NULL,
  DEC_PROP_2 NUMERIC(13,4) NULL,
  BOOL_PROP_1 BOOLEAN NULL,
  BOOL_PROP_2 BOOLEAN NULL,
  TIME_ZONE_ID VARCHAR(80) NULL,
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) REFERENCES {0}TRIGGERS (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
) ENGINE=InnoDB;
--;;
-- {0}BLOB_TRIGGERS
CREATE TABLE IF NOT EXISTS {0}BLOB_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR(200) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  BLOB_DATA BLOB NULL,
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) REFERENCES {0}TRIGGERS (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
) ENGINE=InnoDB;
--;;
-- {0}CALENDARS
CREATE TABLE IF NOT EXISTS {0}CALENDARS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  CALENDAR_NAME VARCHAR(200) NOT NULL,
  CALENDAR BLOB NOT NULL,
  PRIMARY KEY (SCHED_NAME,CALENDAR_NAME)
) ENGINE=InnoDB;
--;;
-- {0}PAUSED_TRIGGER_GRPS
CREATE TABLE IF NOT EXISTS {0}PAUSED_TRIGGER_GRPS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  PRIMARY KEY (SCHED_NAME,TRIGGER_GROUP)
) ENGINE=InnoDB;
--;;
-- {0}PAUSED_JOB_GRPS
CREATE TABLE IF NOT EXISTS {0}PAUSED_JOB_GRPS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  JOB_GROUP VARCHAR(200) NOT NULL,
  PRIMARY KEY (SCHED_NAME,JOB_GROUP)
) ENGINE=InnoDB;
--;;
-- {0}FIRED_TRIGGERS
CREATE TABLE IF NOT EXISTS {0}FIRED_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  ENTRY_ID VARCHAR(140) NOT NULL,
  TRIGGER_NAME VARCHAR(200) NOT NULL,
  TRIGGER_GROUP VARCHAR(200) NOT NULL,
  INSTANCE_NAME VARCHAR(200) NOT NULL,
  FIRED_TIME BIGINT NOT NULL,
  SCHED_TIME BIGINT NOT NULL,
  PRIORITY INTEGER NOT NULL,
  STATE VARCHAR(16) NOT NULL,
  JOB_NAME VARCHAR(200) NULL,
  JOB_GROUP VARCHAR(200) NULL,
  IS_NONCONCURRENT BOOLEAN NULL,
  REQUESTS_RECOVERY BOOLEAN NULL,
  EXECUTION_GROUP VARCHAR(200) NULL,
  PRIMARY KEY (SCHED_NAME,ENTRY_ID),
  KEY IDX_{1}FT_INST_JOB_REQ_RCVRY (SCHED_NAME,INSTANCE_NAME,REQUESTS_RECOVERY),
  KEY IDX_{1}FT_J_G (SCHED_NAME,JOB_NAME,JOB_GROUP),
  KEY IDX_{1}FT_T_G (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
) ENGINE=InnoDB;
--;;
-- {0}SCHEDULER_STATE
CREATE TABLE IF NOT EXISTS {0}SCHEDULER_STATE (
  SCHED_NAME VARCHAR(120) NOT NULL,
  INSTANCE_NAME VARCHAR(200) NOT NULL,
  LAST_CHECKIN_TIME BIGINT NOT NULL,
  CHECKIN_INTERVAL BIGINT NOT NULL,
  PRIMARY KEY (SCHED_NAME,INSTANCE_NAME)
) ENGINE=InnoDB;
--;;
-- {0}LOCKS
CREATE TABLE IF NOT EXISTS {0}LOCKS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  LOCK_NAME VARCHAR(40) NOT NULL,
  PRIMARY KEY (SCHED_NAME,LOCK_NAME)
) ENGINE=InnoDB;
