--
-- Quartz.NET schema -- SQLite
--
-- GENERATED FILE. Describe the schema in build/Build.DatabaseSchema.cs and run
-- 'dotnet fallout GenerateSchema'; edits made here are overwritten.
--
-- This is what AdoJobStore runs for itself when SchemaProvisioning.CreateIfMissing is
-- configured. It is not the script to run by hand -- use
-- database/tables/tables_sqlite.sql for that, which is written for a person with a
-- database client and drops an existing schema before it recreates one.
--
-- Every statement creates only what is missing, and nothing here ever drops anything.
-- So it is safe to run against a schema that already exists, and safe to run twice.
--
-- '{0}' is the configured table prefix and '{1}' is the same prefix with any schema
-- qualifier removed, for the identifiers that cannot carry one -- index, constraint and
-- catalog-lookup names. They are substituted at runtime, so a schema provisioned under a
-- prefix of its own collides with nothing.
--
-- Statements are separated by a line reading exactly '--;;'. The job store splits on
-- it and sends each piece to the provider as one command, which is why no dialect's batch
-- separator appears: no GO, no lone '/', no SET TERM.
--
--;;
-- {0}JOB_DETAILS
CREATE TABLE IF NOT EXISTS {0}JOB_DETAILS (
  SCHED_NAME NVARCHAR(120) NOT NULL,
  JOB_NAME NVARCHAR(150) NOT NULL,
  JOB_GROUP NVARCHAR(150) NOT NULL,
  DESCRIPTION NVARCHAR(250) NULL,
  JOB_CLASS_NAME NVARCHAR(250) NOT NULL,
  IS_DURABLE BIT NOT NULL,
  IS_NONCONCURRENT BIT NOT NULL,
  IS_UPDATE_DATA BIT NOT NULL,
  REQUESTS_RECOVERY BIT NOT NULL,
  JOB_DATA BLOB NULL,
  PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP)
);
--;;
-- {0}TRIGGERS
CREATE TABLE IF NOT EXISTS {0}TRIGGERS (
  SCHED_NAME NVARCHAR(120) NOT NULL,
  TRIGGER_NAME NVARCHAR(150) NOT NULL,
  TRIGGER_GROUP NVARCHAR(150) NOT NULL,
  JOB_NAME NVARCHAR(150) NOT NULL,
  JOB_GROUP NVARCHAR(150) NOT NULL,
  DESCRIPTION NVARCHAR(250) NULL,
  NEXT_FIRE_TIME BIGINT NULL,
  PREV_FIRE_TIME BIGINT NULL,
  PRIORITY INTEGER NULL,
  TRIGGER_STATE NVARCHAR(16) NOT NULL,
  TRIGGER_TYPE NVARCHAR(8) NOT NULL,
  START_TIME BIGINT NOT NULL,
  END_TIME BIGINT NULL,
  CALENDAR_NAME NVARCHAR(200) NULL,
  MISFIRE_INSTR INTEGER NULL,
  MISFIRE_ORIG_FIRE_TIME INTEGER NULL,
  EXECUTION_GROUP NVARCHAR(200) NULL,
  PREFERRED_NODE NVARCHAR(200) NULL,
  PREFERRED_NODE_AUTO BIT NOT NULL DEFAULT 0,
  RETRY_POLICY NVARCHAR(250) NULL,
  RETRY_ATTEMPT INTEGER NULL,
  JOB_DATA BLOB NULL,
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME,JOB_NAME,JOB_GROUP) REFERENCES {0}JOB_DETAILS (SCHED_NAME,JOB_NAME,JOB_GROUP)
);
--;;
-- {0}SIMPLE_TRIGGERS
CREATE TABLE IF NOT EXISTS {0}SIMPLE_TRIGGERS (
  SCHED_NAME NVARCHAR(120) NOT NULL,
  TRIGGER_NAME NVARCHAR(150) NOT NULL,
  TRIGGER_GROUP NVARCHAR(150) NOT NULL,
  REPEAT_COUNT BIGINT NOT NULL,
  REPEAT_INTERVAL BIGINT NOT NULL,
  TIMES_TRIGGERED BIGINT NOT NULL,
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) REFERENCES {0}TRIGGERS (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) ON DELETE CASCADE
);
--;;
-- {0}CRON_TRIGGERS
CREATE TABLE IF NOT EXISTS {0}CRON_TRIGGERS (
  SCHED_NAME NVARCHAR(120) NOT NULL,
  TRIGGER_NAME NVARCHAR(150) NOT NULL,
  TRIGGER_GROUP NVARCHAR(150) NOT NULL,
  CRON_EXPRESSION NVARCHAR(250) NOT NULL,
  TIME_ZONE_ID NVARCHAR(80),
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) REFERENCES {0}TRIGGERS (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) ON DELETE CASCADE
);
--;;
-- {0}SIMPROP_TRIGGERS
CREATE TABLE IF NOT EXISTS {0}SIMPROP_TRIGGERS (
  SCHED_NAME NVARCHAR(120) NOT NULL,
  TRIGGER_NAME NVARCHAR(150) NOT NULL,
  TRIGGER_GROUP NVARCHAR(150) NOT NULL,
  STR_PROP_1 NVARCHAR(512) NULL,
  STR_PROP_2 NVARCHAR(512) NULL,
  STR_PROP_3 NVARCHAR(512) NULL,
  INT_PROP_1 INT NULL,
  INT_PROP_2 INT NULL,
  LONG_PROP_1 BIGINT NULL,
  LONG_PROP_2 BIGINT NULL,
  DEC_PROP_1 NUMERIC NULL,
  DEC_PROP_2 NUMERIC NULL,
  BOOL_PROP_1 BIT NULL,
  BOOL_PROP_2 BIT NULL,
  TIME_ZONE_ID NVARCHAR(80) NULL,
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) REFERENCES {0}TRIGGERS (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) ON DELETE CASCADE
);
--;;
-- {0}BLOB_TRIGGERS
CREATE TABLE IF NOT EXISTS {0}BLOB_TRIGGERS (
  SCHED_NAME NVARCHAR(120) NOT NULL,
  TRIGGER_NAME NVARCHAR(150) NOT NULL,
  TRIGGER_GROUP NVARCHAR(150) NOT NULL,
  BLOB_DATA BLOB NULL,
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) REFERENCES {0}TRIGGERS (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) ON DELETE CASCADE
);
--;;
-- {0}CALENDARS
CREATE TABLE IF NOT EXISTS {0}CALENDARS (
  SCHED_NAME NVARCHAR(120) NOT NULL,
  CALENDAR_NAME NVARCHAR(200) NOT NULL,
  CALENDAR BLOB NOT NULL,
  PRIMARY KEY (SCHED_NAME,CALENDAR_NAME)
);
--;;
-- {0}PAUSED_TRIGGER_GRPS
CREATE TABLE IF NOT EXISTS {0}PAUSED_TRIGGER_GRPS (
  SCHED_NAME NVARCHAR(120) NOT NULL,
  TRIGGER_GROUP NVARCHAR(150) NOT NULL,
  PRIMARY KEY (SCHED_NAME,TRIGGER_GROUP)
);
--;;
-- {0}PAUSED_JOB_GRPS
CREATE TABLE IF NOT EXISTS {0}PAUSED_JOB_GRPS (
  SCHED_NAME NVARCHAR(120) NOT NULL,
  JOB_GROUP NVARCHAR(150) NOT NULL,
  PRIMARY KEY (SCHED_NAME,JOB_GROUP)
);
--;;
-- {0}FIRED_TRIGGERS
CREATE TABLE IF NOT EXISTS {0}FIRED_TRIGGERS (
  SCHED_NAME NVARCHAR(120) NOT NULL,
  ENTRY_ID NVARCHAR(140) NOT NULL,
  TRIGGER_NAME NVARCHAR(150) NOT NULL,
  TRIGGER_GROUP NVARCHAR(150) NOT NULL,
  INSTANCE_NAME NVARCHAR(200) NOT NULL,
  FIRED_TIME BIGINT NOT NULL,
  SCHED_TIME BIGINT NOT NULL,
  PRIORITY INTEGER NOT NULL,
  STATE NVARCHAR(16) NOT NULL,
  JOB_NAME NVARCHAR(150) NULL,
  JOB_GROUP NVARCHAR(150) NULL,
  IS_NONCONCURRENT BIT NULL,
  REQUESTS_RECOVERY BIT NULL,
  EXECUTION_GROUP NVARCHAR(200) NULL,
  PRIMARY KEY (SCHED_NAME,ENTRY_ID)
);
--;;
-- {0}SCHEDULER_STATE
CREATE TABLE IF NOT EXISTS {0}SCHEDULER_STATE (
  SCHED_NAME NVARCHAR(120) NOT NULL,
  INSTANCE_NAME NVARCHAR(200) NOT NULL,
  LAST_CHECKIN_TIME BIGINT NOT NULL,
  CHECKIN_INTERVAL BIGINT NOT NULL,
  PRIMARY KEY (SCHED_NAME,INSTANCE_NAME)
);
--;;
-- {0}LOCKS
CREATE TABLE IF NOT EXISTS {0}LOCKS (
  SCHED_NAME NVARCHAR(120) NOT NULL,
  LOCK_NAME NVARCHAR(40) NOT NULL,
  PRIMARY KEY (SCHED_NAME,LOCK_NAME)
);
--;;
-- {0}DELETE_SIMPLE_TRIGGER
CREATE TRIGGER IF NOT EXISTS {0}DELETE_SIMPLE_TRIGGER DELETE ON {0}TRIGGERS
BEGIN
  DELETE FROM {0}SIMPLE_TRIGGERS WHERE SCHED_NAME=OLD.SCHED_NAME AND TRIGGER_NAME=OLD.TRIGGER_NAME AND TRIGGER_GROUP=OLD.TRIGGER_GROUP;
END
--;;
-- {0}DELETE_SIMPROP_TRIGGER
CREATE TRIGGER IF NOT EXISTS {0}DELETE_SIMPROP_TRIGGER DELETE ON {0}TRIGGERS
BEGIN
  DELETE FROM {0}SIMPROP_TRIGGERS WHERE SCHED_NAME=OLD.SCHED_NAME AND TRIGGER_NAME=OLD.TRIGGER_NAME AND TRIGGER_GROUP=OLD.TRIGGER_GROUP;
END
--;;
-- {0}DELETE_CRON_TRIGGER
CREATE TRIGGER IF NOT EXISTS {0}DELETE_CRON_TRIGGER DELETE ON {0}TRIGGERS
BEGIN
  DELETE FROM {0}CRON_TRIGGERS WHERE SCHED_NAME=OLD.SCHED_NAME AND TRIGGER_NAME=OLD.TRIGGER_NAME AND TRIGGER_GROUP=OLD.TRIGGER_GROUP;
END
--;;
-- {0}DELETE_BLOB_TRIGGER
CREATE TRIGGER IF NOT EXISTS {0}DELETE_BLOB_TRIGGER DELETE ON {0}TRIGGERS
BEGIN
  DELETE FROM {0}BLOB_TRIGGERS WHERE SCHED_NAME=OLD.SCHED_NAME AND TRIGGER_NAME=OLD.TRIGGER_NAME AND TRIGGER_GROUP=OLD.TRIGGER_GROUP;
END
--;;
-- IDX_{1}J_G_N
CREATE INDEX IF NOT EXISTS IDX_{1}J_G_N ON {0}JOB_DETAILS(SCHED_NAME,JOB_GROUP,JOB_NAME);
--;;
-- IDX_{1}T_J
CREATE INDEX IF NOT EXISTS IDX_{1}T_J ON {0}TRIGGERS(SCHED_NAME,JOB_NAME,JOB_GROUP);
--;;
-- IDX_{1}T_G_N
CREATE INDEX IF NOT EXISTS IDX_{1}T_G_N ON {0}TRIGGERS(SCHED_NAME,TRIGGER_GROUP,TRIGGER_NAME);
--;;
-- IDX_{1}T_C
CREATE INDEX IF NOT EXISTS IDX_{1}T_C ON {0}TRIGGERS(SCHED_NAME,CALENDAR_NAME);
--;;
-- IDX_{1}T_NFT_ST
CREATE INDEX IF NOT EXISTS IDX_{1}T_NFT_ST ON {0}TRIGGERS(SCHED_NAME,TRIGGER_STATE,NEXT_FIRE_TIME);
--;;
-- IDX_{1}FT_INST_JOB_REQ_RCVRY
CREATE INDEX IF NOT EXISTS IDX_{1}FT_INST_JOB_REQ_RCVRY ON {0}FIRED_TRIGGERS(SCHED_NAME,INSTANCE_NAME,REQUESTS_RECOVERY);
--;;
-- IDX_{1}FT_J_G
CREATE INDEX IF NOT EXISTS IDX_{1}FT_J_G ON {0}FIRED_TRIGGERS(SCHED_NAME,JOB_NAME,JOB_GROUP);
--;;
-- IDX_{1}FT_T_G
CREATE INDEX IF NOT EXISTS IDX_{1}FT_T_G ON {0}FIRED_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP);
