#region License

/*
 * All content copyright Marko Lahma, unless otherwise indicated. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 */

#endregion

using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

using Quartz.Impl.AdoJobStore;

namespace Quartz.Tests.Unit.Impl.AdoJobStore;

/// <summary>
/// Every fresh-install script says what the generated create-if-missing script for its dialect says.
/// </summary>
/// <remarks>
/// <para>
/// <c>database/tables/tables_&lt;script&gt;.sql</c> is hand-written and read by people;
/// <c>Impl/AdoJobStore/Schema/create_&lt;dialect&gt;.sql</c> is generated by
/// <c>dotnet fallout GenerateSchema</c> and run by the job store. Eight scripts, six models, one schema —
/// and nothing but this stops them drifting until an integration leg with a container of that database
/// gets to run. The memory-optimized and pre-2016 SQL Server scripts have no container at all, which is
/// how 4.2.0 shipped both without <c>RETRY_ATTEMPT</c>, so they are held to <c>create_sqlServer.sql</c>
/// here like the rest.
/// </para>
/// <para>
/// Both kinds of script are parsed by <see cref="SqlObjects" /> and what it finds is compared: tables,
/// each column's type, nullability and default, primary keys, foreign keys by shape, and each index's
/// columns and directions. What a script may legitimately say differently is in
/// <see cref="Exemptions" />, each with its reason. <c>SchemaProvisioningTest</c> is the other half and
/// does need a database: it provisions into a real one of each dialect and compares the catalog.
/// </para>
/// </remarks>
public class SchemaScriptTest
{
    private static readonly string[] Dialects = MigrationFiles.Dialects;

    /// <summary>
    /// Every fresh-install script: one per dialect, and the two SQL Server variants, which are held to
    /// the SQL Server model.
    /// </summary>
    private static readonly string[] EveryFreshInstallScript =
        [.. Dialects, "sqlServerMOT", "sqlServer_Below2016"];

    /// <summary>Every script but the one whose indexes take a single direction for the whole index.</summary>
    private static readonly string[] ScriptsThatIndexPerColumnDirection =
        [.. EveryFreshInstallScript.Where(d => d != "firebird")];

    /// <summary>
    /// Where a fresh-install script declares a table differently from the model on purpose, by script and
    /// table, and why. Columns and primary key are not compared there; the table's existence, its foreign
    /// keys and its indexes still are.
    /// </summary>
    private static readonly Dictionary<(string Script, string Table), string> Exemptions = new()
    {
        [("sqlServerMOT", "LOCKS")] =
            "a memory-optimized table needs a primary key of its own, so QRTZ_LOCKS gains a uniqueidentifier ID "
            + "with a NONCLUSTERED HASH key, and the two key columns a BIN2 collation, which a memory-optimized "
            + "table requires of an indexed string",
    };

    /// <summary>The line the job store splits the script on.</summary>
    private const string StatementSeparator = "--;;";

    /// <summary>The acquisition index, as the parser names it once the table prefix is off.</summary>
    private const string AcquisitionIndexName = "IDX_T_NFT_ST";

    /// <summary>The index 4.0 stopped creating, named the same way.</summary>
    private const string MisfireIndexName = "IDX_T_NFT_ST_MISFIRE";

    /// <summary>
    /// The columns the acquisition index is declared over, built from the order acquisition reads in
    /// rather than written out beside it.
    /// </summary>
    /// <remarks>
    /// The middle of this list <em>is</em> the statement's <c>ORDER BY</c>: the index exists to answer
    /// that clause with an ordered seek, and it can only do so while the two agree on the columns, the
    /// order and the directions. Deriving one from the other is what makes a change to the clause fail
    /// here against every dialect's script, instead of passing every test and costing a sort
    /// (<see href="https://github.com/quartznet/quartznet/issues/3625">#3625</see>).
    /// </remarks>
    private static readonly string AcquisitionIndexColumns = string.Join(", ",
        AdoConstants.ColumnSchedulerName,
        AdoConstants.ColumnTriggerState,
        StdAdoConstants.TriggerSweepOrderBy(alias: ""),
        AdoConstants.ColumnMisfireInstruction);

    /// <summary>
    /// The same list as far as Firebird can express it: the leading column of the sweep order, with no
    /// direction on it and nothing after it. Derived for the same reason, so that reordering the sweep
    /// moves this dialect's expectation with the rest.
    /// </summary>
    private static readonly string FirebirdAcquisitionIndexColumns = string.Join(", ",
        AdoConstants.ColumnSchedulerName,
        AdoConstants.ColumnTriggerState,
        StdAdoConstants.TriggerSweepOrder[0].Column);

    [TestCaseSource(nameof(EveryFreshInstallScript))]
    public void TheGeneratedScriptCreatesTheTablesTheFreshInstallScriptCreates(string script)
    {
        SqlObjects generated = Generated(script);
        SqlObjects fresh = FreshInstall(script);

        fresh.Tables.Should().NotBeEmpty(
            "the fresh-install script has to parse for the comparison to mean anything");

        generated.Tables.Keys.Should().BeEquivalentTo(fresh.Tables.Keys,
            $"a table in database/tables/tables_{script}.sql and not in the generated script is one "
            + "SchemaProvisioning.CreateIfMissing leaves out, and one the store validates for immediately "
            + "afterwards");
    }

    /// <summary>
    /// The third file in the pair's conversation: the list the store probes at startup.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The two scripts agreeing with each other is not enough, because both can create a table the
    /// store never asks about. <c>AdoConstants.AllTableNames</c> is what
    /// <see cref="SchemaProvisioning.Validate" /> runs a <c>SELECT 1</c> against, so a table in the
    /// scripts and not in that list is one a database can be missing while startup reports the schema
    /// good — which is what #3564 was, about <c>QRTZ_SIMPROP_TRIGGERS</c>.
    /// </para>
    /// <para>
    /// <c>AdoConstants.OptionalTableNames</c> is the other half of the answer, and it is the whole of
    /// the exemption: a table there is probed when the feature that needs it is turned on and never
    /// otherwise. Every other table the scripts create still has to be one startup checks for
    /// unconditionally.
    /// </para>
    /// </remarks>
    [TestCaseSource(nameof(EveryFreshInstallScript))]
    public void EveryTableTheFreshInstallScriptCreatesIsOneTheStoreValidates(string script)
    {
        FreshInstall(script).Tables.Keys.Should().BeEquivalentTo(EveryTableTheStoreKnows,
            $"database/tables/tables_{script}.sql, AdoConstants.AllTableNames and "
            + "AdoConstants.OptionalTableNames describe the same schema — one creates it, the other two "
            + "are the whole of what startup checks is there, unconditionally and on demand");
    }

    /// <summary>
    /// Every optional table is created by the migration it names, and nothing after 4.0 creates a table
    /// that is not optional.
    /// </summary>
    /// <remarks>
    /// The comparison above passes just as happily if an optional table were moved into
    /// <c>AllTableNames</c>, which would make its migration mandatory for every database that never
    /// turned the feature on — the one thing #3771 says it must not be. So the split is asserted, and it
    /// is asserted against the migration folders rather than against a list: a migration after 4.0 that
    /// creates a table is an optional one, and its entry has to name that very file so the startup
    /// failure can.
    /// </remarks>
    [Test]
    public void EveryOptionalTableIsCreatedByTheMigrationItNames()
    {
        AdoConstants.OptionalTableNames.Select(t => t.Table).Should().NotIntersectWith(AdoConstants.AllTableNames,
            "a table in the unconditional probe makes its migration mandatory for every database, so it "
            + "cannot also be one a database may be without");

        AdoConstants.OptionalTableNames.Select(t => AdoConstants.MigrationVersion(t.Migration)).Should().BeInAscendingOrder(
            "a table a later migration creates comes after the tables it sits beside, so a database without "
            + "the feature at all is told about the oldest script first");

        foreach (string dialect in Dialects)
        {
            Dictionary<string, string> scripts = MigrationFiles.For(dialect, "4.0", inclusive: false)
                .ToDictionary(x => x.Path, x => x.Text, StringComparer.Ordinal);

            foreach ((string table, string migration, _) in AdoConstants.OptionalTableNames)
            {
                string path = MigrationFiles.PathOf(migration, dialect);

                scripts.Should().ContainKey(path,
                    $"QRTZ_{table} names {migration}, and every migration ships a file for every dialect");
                MigrationFiles.CreatedTables(scripts[path]).Should().Contain(table,
                    $"{path} is the script the store names when QRTZ_{table} is missing, so it has to be the "
                    + "one that creates it");
            }

            List<string> strays = scripts
                .SelectMany(x => MigrationFiles.CreatedTables(x.Value).Select(table => (Path: x.Key, Table: table)))
                .Where(x => !AdoConstants.OptionalTableNames.Any(t =>
                    t.Table == x.Table && MigrationFiles.PathOf(t.Migration, dialect) == x.Path))
                .Select(x => $"{x.Path} creates QRTZ_{x.Table}")
                .ToList();

            strays.Should().BeEmpty(
                "a table a migration after 4.0 creates is one a 4.0 database lacks, so it has to be optional "
                + "and name that migration in AdoConstants.OptionalTableNames — required, it would refuse "
                + "every database that has not run the script");
        }
    }

    /// <summary>Every table the store knows about, required and optional alike.</summary>
    private static readonly string[] EveryTableTheStoreKnows =
        [.. AdoConstants.AllTableNames, .. AdoConstants.OptionalTableNames.Select(t => t.Table)];

    /// <summary>
    /// Each column is declared with the type, nullability and default the model gives it.
    /// </summary>
    /// <remarks>
    /// A column only one script has, and one whose declaration differs, are both drift nothing below the
    /// integration legs would otherwise notice — and nothing at all notices it in the two SQL Server
    /// variants, which no leg runs.
    /// </remarks>
    [TestCaseSource(nameof(EveryFreshInstallScript))]
    public void TheFreshInstallScriptDeclaresEachColumnAsTheGeneratedScriptDoes(string script)
    {
        SqlObjects generated = Generated(script);
        SqlObjects fresh = FreshInstall(script);

        // Guards the guard: a parser that found no columns would make the loop below vacuous, and
        // every table Quartz has holds at least SCHED_NAME and one more.
        fresh.Tables.Should().AllSatisfy(table => table.Value.Should().HaveCountGreaterThan(1));

        List<string> differences = [];

        foreach ((string table, Dictionary<string, SqlColumn> columns) in fresh.Tables)
        {
            if (Exempt(script, table) || !generated.Tables.TryGetValue(table, out Dictionary<string, SqlColumn> modelled))
            {
                continue;
            }

            foreach ((string column, SqlColumn declared) in columns)
            {
                if (!modelled.TryGetValue(column, out SqlColumn expected))
                {
                    differences.Add($"{table}.{column} is only in the fresh-install script");
                }
                else if (declared != expected)
                {
                    differences.Add($"{table}.{column} is {declared} in the fresh-install script and {expected} in the generated one");
                }
            }

            differences.AddRange(modelled.Keys.Except(columns.Keys, StringComparer.Ordinal)
                .Select(missing => $"{table}.{missing} is only in the generated script"));
        }

        differences.Should().BeEmpty(
            $"database/tables/tables_{script}.sql and create_{Counterpart(script)}.sql describe one schema, "
            + "column by column");
    }

    [TestCaseSource(nameof(EveryFreshInstallScript))]
    public void TheFreshInstallScriptKeysEachTableAsTheGeneratedScriptDoes(string script)
    {
        SqlObjects generated = Generated(script);
        SqlObjects fresh = FreshInstall(script);

        fresh.PrimaryKeys.Keys.Should().BeEquivalentTo(fresh.Tables.Keys,
            "every Quartz table has a primary key, so a table the parse found none on is a parse that missed it");

        foreach ((string table, string columns) in fresh.PrimaryKeys.Where(x => !Exempt(script, x.Key)))
        {
            generated.PrimaryKeys.Should().ContainKey(table)
                .WhoseValue.Should().Be(columns,
                    $"QRTZ_{table}'s key is what every statement that writes it relies on being unique, so "
                    + $"tables_{script}.sql and the generated script have to key it on the same columns, in "
                    + "the same order");
        }
    }

    /// <summary>
    /// The foreign keys are the same keys, compared by what they join and whether a delete cascades —
    /// never by name, which a dialect that leaves a key unnamed lets the database choose.
    /// </summary>
    /// <remarks>
    /// <c>create_sqlServer.sql</c> once had one on <c>QRTZ_BLOB_TRIGGERS</c> that
    /// <c>tables_sqlServer.sql</c> has never had
    /// (<see href="https://github.com/quartznet/quartznet/issues/3949">#3949</see>), and nothing noticed
    /// until a Weasel model had to be told which of the two to believe.
    /// </remarks>
    [TestCaseSource(nameof(EveryFreshInstallScript))]
    public void TheFreshInstallScriptHasTheForeignKeysTheGeneratedScriptHas(string script)
    {
        SqlObjects fresh = FreshInstall(script);

        fresh.ForeignKeys.Should().HaveCountGreaterThan(3,
            "QRTZ_TRIGGERS references its job and the trigger-type tables reference their trigger, so a parse "
            + "that found almost none stopped matching");

        Generated(script).ForeignKeys.Should().Equal(fresh.ForeignKeys,
            $"a database installed from tables_{script}.sql and one ProvisionSchema() created are one schema, "
            + "and a key only one of them has rejects rows on one and not the other");
    }

    [TestCaseSource(nameof(EveryFreshInstallScript))]
    public void TheGeneratedScriptCreatesTheIndexesTheFreshInstallScriptCreates(string script)
    {
        SqlObjects fresh = FreshInstall(script);

        fresh.Indexes.Should().NotBeEmpty("every fresh-install script creates indexes");

        Generated(script).Indexes.Should().BeEquivalentTo(fresh.Indexes,
            "the index set is also the one the 3.x-to-4.0 migration converges onto, so a provisioned "
            + "schema, a migrated one and one installed from the script all have to end up with the same "
            + "indexes — over the same columns, in the same order, with the same directions, since an "
            + "index that matches only by name serves a different set of plans");
    }

    /// <summary>
    /// Every fresh-install script drops each table it creates before it creates the first one.
    /// </summary>
    /// <remarks>
    /// The teardown is what makes a script re-runnable over the schema it installed, and each dialect
    /// writes it differently — a bracketed <c>DROP TABLE</c>, MySQL's one list, Oracle's procedure, a
    /// Firebird <c>EXECUTE STATEMENT</c>. A table added to the creates and not to the drops makes the
    /// second run fail on a table that already exists.
    /// </remarks>
    [TestCaseSource(nameof(EveryFreshInstallScript))]
    public void EveryFreshInstallScriptTearsDownEveryTableItCreates(string script)
    {
        string text = FreshInstallScript(script);
        HashSet<string> dropped = SqlObjects.TornDown(text);

        dropped.Should().NotBeEmpty($"tables_{script}.sql opens by dropping the schema it is about to create");

        FreshInstall(script).Tables.Keys.Should().BeSubsetOf(dropped,
            $"a table tables_{script}.sql creates and does not drop first is one the script's second run "
            + "fails on");
    }

    /// <summary>
    /// The acquisition index carries the order acquisition reads in
    /// (<see href="https://github.com/quartznet/quartznet/issues/3510">#3510</see>).
    /// </summary>
    /// <remarks>
    /// <c>SelectNextTriggerToAcquire</c> orders by <c>NEXT_FIRE_TIME ASC, PRIORITY DESC</c> and every
    /// dialect splices its row limit into the statement, so the <c>ORDER BY</c> decides which rows
    /// come back at all. An index whose two directions match lets the engine take the first entry
    /// instead of reading every candidate and sorting; <c>MISFIRE_INSTR</c> keeps that ordered seek
    /// from looking up a backlogged row it is only going to reject. Neither is visible from the
    /// index's name, which is why this is asserted rather than left to the comparison above.
    /// </remarks>
    [TestCaseSource(nameof(ScriptsThatIndexPerColumnDirection))]
    public void TheAcquisitionIndexCarriesTheDirectionsAcquisitionOrdersBy(string script)
    {
        FreshInstall(script).Indexes
            .Should().ContainKey(AcquisitionIndexName)
            .WhoseValue.Should().Be(AcquisitionIndexColumns,
                $"database/tables/tables_{script}.sql is what a person installs a schema from, and "
                + "an acquisition index without the descending priority costs a sort of every due "
                + "trigger on every acquisition attempt");

        Generated(script).Indexes
            .Should().ContainKey(AcquisitionIndexName)
            .WhoseValue.Should().Be(AcquisitionIndexColumns,
                "SchemaProvisioning.CreateIfMissing has to reach the same schema the fresh-install "
                + "script reaches, and this index is the one that decides what acquisition costs");
    }

    /// <summary>
    /// The statements and the index lists above are one definition read two ways.
    /// </summary>
    /// <remarks>
    /// <see cref="AcquisitionIndexColumns" /> is built from <c>StdAdoConstants.TriggerSweepOrder</c>, so
    /// a reordering moves both sides together and cannot be seen there. What this checks is the other
    /// half: that the statements really are written from that definition rather than spelling an order
    /// of their own beside it. Together the two make a change to either the clause or the index fail a
    /// test, which is what #3625 found nothing did.
    /// </remarks>
    [Test]
    public void TheSweepStatementsOrderByTheColumnsTheIndexesAreDeclaredOver()
    {
        string order = StdAdoConstants.TriggerSweepOrderBy(alias: "");

        order.Should().Be("NEXT_FIRE_TIME ASC, PRIORITY DESC",
            "the earliest due trigger first and the highest priority among ties is what the two sweeps "
            + "mean, and writing it out once here is what keeps the derivation below from being vacuous");

        StdAdoConstants.SqlSelectNextTriggerToAcquire.Should().EndWith(order,
            "acquisition orders by the definition the acquisition index is declared over — an index "
            + "whose directions disagree with the clause cannot answer it with an ordered seek");

        AcquisitionIndexColumns.Should().Contain(order,
            "which is only true while the index list is built from the same definition");

        StdAdoConstants.SqlSelectMisfiredTriggersToRecover.Should().EndWith(
            StdAdoConstants.TriggerSweepOrderBy(alias: "t."),
            "misfire recovery reads the backlog in the same order, aliased because its statement joins");
    }

    /// <summary>
    /// Firebird's acquisition index is the three-column one, deliberately.
    /// </summary>
    /// <remarks>
    /// A Firebird index is ascending or descending as a whole, so <c>CREATE INDEX</c> rejects the
    /// <c>ASC</c> token outright, and a <c>COMPUTED BY</c> column standing in for a negated priority
    /// cannot be indexed either — <c>attempt to index COMPUTED BY column</c>. Acquisition there still
    /// materialises its candidates and sorts them. <c>MISFIRE_INSTR</c> is left off with the
    /// direction: measured, it buys Firebird nothing without an ordered seek in front of it, and it
    /// would be a wider entry on every write. This asserts the difference so that a later sweep
    /// aligning the dialects has to read why first.
    /// </remarks>
    [Test]
    public void FirebirdKeepsTheThreeColumnAcquisitionIndex()
    {
        FreshInstall("firebird").Indexes
            .Should().ContainKey(AcquisitionIndexName)
            .WhoseValue.Should().Be(FirebirdAcquisitionIndexColumns,
                "Firebird refuses both a per-column direction and an index over the computed column "
                + "that would stand in for one, so this is the widest shape the server accepts");

        Generated("firebird").Indexes
            .Should().ContainKey(AcquisitionIndexName)
            .WhoseValue.Should().Be(FirebirdAcquisitionIndexColumns,
                "a provisioned Firebird schema has to be the one the fresh-install script installs, "
                + "including where that differs from every other dialect");
    }

    /// <summary>
    /// Nothing creates <c>IDX_QRTZ_T_NFT_ST_MISFIRE</c>, and that is a decision rather than an omission
    /// (<see href="https://github.com/quartznet/quartznet/issues/3656">#3656</see>).
    /// </summary>
    /// <remarks>
    /// It led with <c>MISFIRE_INSTR</c>, the column both misfire statements compare with <c>&lt;&gt; -1</c>
    /// and no B-tree can seek past, while those statements filter <c>SCHED_NAME</c> and
    /// <c>TRIGGER_STATE</c> by equality and <c>NEXT_FIRE_TIME</c> by range — the acquisition index's own
    /// leading columns since #3510 reshaped it. Measured plan by plan on all four dialects that created
    /// it, no optimizer picks it for either statement, so it was maintained on every trigger write and
    /// read by nothing. This is asserted rather than left to the comparison above, which would pass a
    /// script that put it back on both sides at once — which is how it would come back.
    /// </remarks>
    [TestCaseSource(nameof(EveryFreshInstallScript))]
    public void NoFreshInstallScriptCreatesTheMisfireIndex(string script)
    {
        FreshInstall(script).Indexes
            .Should().ContainKey(AcquisitionIndexName,
                "the guard is only meaningful while this parse finds the index set at all")
            .And.NotContainKey(MisfireIndexName,
                $"database/tables/tables_{script}.sql is what a person installs a schema from, and this "
                + "index answers neither misfire statement on any engine — it is write cost with no reader");
    }

    [TestCaseSource(nameof(Dialects))]
    public void NoGeneratedScriptCreatesTheMisfireIndex(string dialect)
    {
        Generated(dialect).Indexes
            .Should().NotContainKey(MisfireIndexName,
                "SchemaProvisioning.CreateIfMissing reaches the schema the fresh-install script reaches, "
                + "and a provisioned database that grew this index back would pay for it on every write");
    }

    [Test]
    public void TheGeneratedSqliteScriptCreatesTheDeleteTriggers()
    {
        SqlObjects generated = Generated("sqlite");
        SqlObjects fresh = FreshInstall("sqlite");

        fresh.Triggers.Should().HaveCount(4);

        generated.Triggers.Should().BeEquivalentTo(fresh.Triggers,
            "SQLite does not enforce foreign keys unless the connection asks it to, so these four "
            + "triggers are what deletes a trigger's type row — a provisioned schema without them leaks "
            + "rows into QRTZ_SIMPLE_TRIGGERS and its siblings");
    }

    [Test]
    public void TheSqliteDeleteTriggersCarryTheTablePrefix()
    {
        // Read off the raw text rather than the parsed names, which have had the prefix taken off
        // them so the two scripts can be compared at all.
        Regex declaration = new(@"CREATE\s+TRIGGER\s+(?:IF\s+NOT\s+EXISTS\s+)?(?<name>\S+)",
            RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);

        declaration.Matches(FreshInstallScript("sqlite")).Select(m => m.Groups["name"].Value)
            .Should().AllSatisfy(name => name.Should().StartWith("QRTZ_"))
            .And.HaveCount(4,
                "a trigger name is database-wide in SQLite, so an unprefixed one stopped two Quartz "
                + "schemas sharing a file however their table prefixes were configured");

        declaration.Matches(GeneratedScript("sqlite")).Select(m => m.Groups["name"].Value)
            .Should().AllSatisfy(name => name.Should().StartWith("{0}"))
            .And.HaveCount(4, "the generated script carries the prefix as a placeholder");
    }

    [TestCaseSource(nameof(Dialects))]
    public void NoStatementSpellsTheDefaultPrefixOut(string dialect)
    {
        foreach (string statement in Statements(GeneratedScript(dialect)))
        {
            statement.Should().NotContain("QRTZ_",
                "the prefix is substituted at runtime, so a literal QRTZ_ is an object that ignores the "
                + "configured one — and on a shared database, an object two schedulers fight over");
        }
    }

    [TestCaseSource(nameof(Dialects))]
    public void EveryIndexNameUsesTheUnqualifiedPrefixPlaceholder(string dialect)
    {
        MatchCollection matches = Regex.Matches(GeneratedScript(dialect), @"IDX_\{(?<slot>\d)\}",
            RegexOptions.CultureInvariant);

        matches.Should().NotBeEmpty("every dialect creates indexes, and every index name is prefixed");

        matches.Select(m => m.Groups["slot"].Value).Distinct().Should().Equal(["1"],
            "an index name cannot carry a schema qualifier, so it takes {1} — the prefix with any "
            + "qualifier removed — where a table name takes {0}");
    }

    [TestCaseSource(nameof(Dialects))]
    public void SubstitutingAPrefixLeavesNoPlaceholderBehind(string dialect)
    {
        string substituted = string.Format(CultureInfo.InvariantCulture, GeneratedScript(dialect), "QRTZP_", "QRTZP_");

        substituted.Should().NotContain("{",
            "the job store formats the whole script with string.Format, so a stray brace is a "
            + "FormatException on a scheduler that was starting up");
    }

    [TestCaseSource(nameof(Dialects))]
    public void NoStatementDropsAnything(string dialect)
    {
        foreach (string statement in Statements(GeneratedScript(dialect)))
        {
            statement.Should().NotContainEquivalentOf("DROP ",
                "provisioning creates what is missing and nothing else — a scheduler that could drop a "
                + "table is a scheduler that can lose a production schema to a mis-typed prefix");
        }
    }

    [TestCaseSource(nameof(Dialects))]
    public void NoBatchSeparatorSurvivesIntoTheScript(string dialect)
    {
        string[] lines = Lines(GeneratedScript(dialect));

        lines.Should().NotContain(line => line.Trim().Equals("GO", StringComparison.OrdinalIgnoreCase),
            "GO is sqlcmd's rather than T-SQL's, and a provider rejects it");
        lines.Should().NotContain(line => line.Trim() == "/",
            "a lone slash is SQL*Plus's statement terminator and ODP.NET does not know it");
        lines.Should().NotContain(line => line.TrimStart().StartsWith("SET TERM", StringComparison.OrdinalIgnoreCase),
            "SET TERM is an isql directive; the Firebird provider takes one statement per command");
    }

    [TestCaseSource(nameof(Dialects))]
    public void TheHeaderIsTheOnlyChunkWithNoStatementInIt(string dialect)
    {
        string[] chunks = Chunks(GeneratedScript(dialect));

        chunks.Should().HaveCountGreaterThan(EveryTableTheStoreKnows.Length,
            "one chunk per table at least, so a split that produced fewer means the separator moved and "
            + "the whole file would go to the provider as one command");

        HasStatement(chunks[0]).Should().BeFalse(
            "the header explains the file rather than doing anything, and the job store skips it");

        chunks.Skip(1).Should().AllSatisfy(chunk => HasStatement(chunk).Should().BeTrue(
            "a chunk of nothing but comments anywhere after the header means an object went missing:"
            + Environment.NewLine + chunk));
    }

    // ---------------------------------------------------------------------------------------------
    // Reading the two kinds of script
    // ---------------------------------------------------------------------------------------------

    /// <summary>
    /// The dialect whose model a fresh-install script is held to: its own, or SQL Server's for the two
    /// SQL Server variants.
    /// </summary>
    internal static string Counterpart(string script) => script.StartsWith("sqlServer", StringComparison.Ordinal) ? "sqlServer" : script;

    private static bool Exempt(string script, string table) => Exemptions.ContainsKey((script, table));

    private static SqlObjects Generated(string script) => SqlObjects.Parse(GeneratedScript(Counterpart(script)), Counterpart(script));

    private static SqlObjects FreshInstall(string script) => SqlObjects.Parse(FreshInstallScript(script), Counterpart(script));

    internal static string GeneratedScript(string dialect)
    {
        string name = $"Quartz.Impl.AdoJobStore.Schema.create_{dialect}.sql";

        using Stream stream = typeof(IScheduler).Assembly.GetManifestResourceStream(name)
            ?? throw new InvalidOperationException(
                $"'{name}' is not embedded in Quartz.dll. Run 'dotnet fallout GenerateSchema'.");

        using StreamReader reader = new(stream, Encoding.UTF8);
        return reader.ReadToEnd();
    }

    private static string FreshInstallScript(string script)
    {
        string path = Path.Combine(RepositoryRoot.Find().FullName, "database", "tables", $"tables_{script}.sql");
        return File.ReadAllText(path);
    }

    private static string[] Lines(string script) => script.Replace("\r\n", "\n").Split('\n');

    private static string[] Chunks(string script) =>
        script.Replace("\r\n", "\n").Split($"\n{StatementSeparator}\n");

    private static IEnumerable<string> Statements(string script) => Chunks(script).Where(HasStatement);

    /// <summary>Whether a chunk holds anything but blank lines and whole-line comments.</summary>
    private static bool HasStatement(string chunk) =>
        Lines(chunk).Any(line => line.Trim().Length > 0 && !line.TrimStart().StartsWith("--", StringComparison.Ordinal));
}
