#region License

/*
 * All content copyright Marko Lahma, unless otherwise indicated. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 */

#endregion

using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

namespace Quartz.Tests.Unit.Impl.AdoJobStore;

/// <summary>
/// The embedded create-if-missing scripts say what the fresh-install scripts say.
/// </summary>
/// <remarks>
/// <para>
/// <c>database/tables/tables_&lt;dialect&gt;.sql</c> is hand-written and read by people;
/// <c>Impl/AdoJobStore/Schema/create_&lt;dialect&gt;.sql</c> is generated by
/// <c>dotnet fallout GenerateSchema</c> and run by the job store. Two files, one schema — and
/// nothing but this stops them drifting until an integration leg with a container of that database
/// gets to run.
/// </para>
/// <para>
/// The comparison is textual: both files are parsed with the same small parser and the names it
/// finds are compared. That catches the class of mistake this pair is prone to — a column added to
/// one and not the other, an index renamed, a table forgotten — without needing a database.
/// <c>SchemaProvisioningTest</c> is the other half and does need one: it provisions into a real
/// database of each dialect and compares the catalog, which is where a column that matches by name
/// but not by type shows up.
/// </para>
/// </remarks>
public class SchemaScriptTest
{
    private static readonly string[] Dialects =
        ["sqlServer", "postgres", "mysql_innodb", "oracle", "sqlite", "firebird"];

    /// <summary>The line the job store splits the script on.</summary>
    private const string StatementSeparator = "--;;";

    [TestCaseSource(nameof(Dialects))]
    public void TheGeneratedScriptCreatesTheTablesTheFreshInstallScriptCreates(string dialect)
    {
        SqlObjects generated = SqlObjects.Parse(GeneratedScript(dialect));
        SqlObjects fresh = SqlObjects.Parse(FreshInstallScript(dialect));

        fresh.Tables.Should().NotBeEmpty(
            "the fresh-install script has to parse for the comparison to mean anything");

        generated.Tables.Keys.Should().BeEquivalentTo(fresh.Tables.Keys,
            $"a table in database/tables/tables_{dialect}.sql and not in the generated script is one "
            + "SchemaProvisioning.CreateIfMissing leaves out, and one the store validates for immediately "
            + "afterwards");
    }

    [TestCaseSource(nameof(Dialects))]
    public void TheGeneratedScriptDeclaresTheColumnsTheFreshInstallScriptDeclares(string dialect)
    {
        SqlObjects generated = SqlObjects.Parse(GeneratedScript(dialect));
        SqlObjects fresh = SqlObjects.Parse(FreshInstallScript(dialect));

        // Guards the guard: a parser that found no columns would make the loop below vacuous, and
        // every table Quartz has holds at least SCHED_NAME and one more.
        fresh.Tables.Should().AllSatisfy(table => table.Value.Should().HaveCountGreaterThan(1));

        List<string> differences = [];

        foreach ((string table, List<string> columns) in fresh.Tables)
        {
            if (!generated.Tables.TryGetValue(table, out List<string> generatedColumns))
            {
                continue;
            }

            differences.AddRange(columns.Except(generatedColumns, StringComparer.Ordinal)
                .Select(missing => $"{table}.{missing} is only in the fresh-install script"));

            differences.AddRange(generatedColumns.Except(columns, StringComparer.Ordinal)
                .Select(extra => $"{table}.{extra} is only in the generated script"));
        }

        differences.Should().BeEmpty(
            $"the two {dialect} scripts describe one schema, and a column in only one of them is drift "
            + "that nothing below the integration legs would otherwise notice");
    }

    [TestCaseSource(nameof(Dialects))]
    public void TheGeneratedScriptCreatesTheIndexesTheFreshInstallScriptCreates(string dialect)
    {
        SqlObjects generated = SqlObjects.Parse(GeneratedScript(dialect));
        SqlObjects fresh = SqlObjects.Parse(FreshInstallScript(dialect));

        fresh.Indexes.Should().NotBeEmpty("every dialect's fresh-install script creates indexes");

        generated.Indexes.Should().BeEquivalentTo(fresh.Indexes,
            "the index set is also the one the 3.x-to-4.0 migration converges onto, so a provisioned "
            + "schema, a migrated one and one installed from the script all have to end up with the same "
            + "indexes");
    }

    [Test]
    public void TheGeneratedSqliteScriptCreatesTheDeleteTriggers()
    {
        SqlObjects generated = SqlObjects.Parse(GeneratedScript("sqlite"));
        SqlObjects fresh = SqlObjects.Parse(FreshInstallScript("sqlite"));

        fresh.Triggers.Should().HaveCount(4);

        generated.Triggers.Should().BeEquivalentTo(fresh.Triggers,
            "SQLite does not enforce foreign keys unless the connection asks it to, so these four "
            + "triggers are what deletes a trigger's type row — a provisioned schema without them leaks "
            + "rows into QRTZ_SIMPLE_TRIGGERS and its siblings");
    }

    [Test]
    public void TheSqliteDeleteTriggersCarryTheTablePrefix()
    {
        // Read off the raw text rather than the parsed names, which have had the prefix taken off
        // them so the two scripts can be compared at all.
        Regex declaration = new(@"CREATE\s+TRIGGER\s+(?:IF\s+NOT\s+EXISTS\s+)?(?<name>\S+)",
            RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);

        declaration.Matches(FreshInstallScript("sqlite")).Select(m => m.Groups["name"].Value)
            .Should().AllSatisfy(name => name.Should().StartWith("QRTZ_"))
            .And.HaveCount(4,
                "a trigger name is database-wide in SQLite, so an unprefixed one stopped two Quartz "
                + "schemas sharing a file however their table prefixes were configured");

        declaration.Matches(GeneratedScript("sqlite")).Select(m => m.Groups["name"].Value)
            .Should().AllSatisfy(name => name.Should().StartWith("{0}"))
            .And.HaveCount(4, "the generated script carries the prefix as a placeholder");
    }

    [TestCaseSource(nameof(Dialects))]
    public void NoStatementSpellsTheDefaultPrefixOut(string dialect)
    {
        foreach (string statement in Statements(GeneratedScript(dialect)))
        {
            statement.Should().NotContain("QRTZ_",
                "the prefix is substituted at runtime, so a literal QRTZ_ is an object that ignores the "
                + "configured one — and on a shared database, an object two schedulers fight over");
        }
    }

    [TestCaseSource(nameof(Dialects))]
    public void EveryIndexNameUsesTheUnqualifiedPrefixPlaceholder(string dialect)
    {
        MatchCollection matches = Regex.Matches(GeneratedScript(dialect), @"IDX_\{(?<slot>\d)\}",
            RegexOptions.CultureInvariant);

        matches.Should().NotBeEmpty("every dialect creates indexes, and every index name is prefixed");

        matches.Select(m => m.Groups["slot"].Value).Distinct().Should().Equal(["1"],
            "an index name cannot carry a schema qualifier, so it takes {1} — the prefix with any "
            + "qualifier removed — where a table name takes {0}");
    }

    [TestCaseSource(nameof(Dialects))]
    public void SubstitutingAPrefixLeavesNoPlaceholderBehind(string dialect)
    {
        string substituted = string.Format(CultureInfo.InvariantCulture, GeneratedScript(dialect), "QRTZP_", "QRTZP_");

        substituted.Should().NotContain("{",
            "the job store formats the whole script with string.Format, so a stray brace is a "
            + "FormatException on a scheduler that was starting up");
    }

    [TestCaseSource(nameof(Dialects))]
    public void NoStatementDropsAnything(string dialect)
    {
        foreach (string statement in Statements(GeneratedScript(dialect)))
        {
            statement.Should().NotContainEquivalentOf("DROP ",
                "provisioning creates what is missing and nothing else — a scheduler that could drop a "
                + "table is a scheduler that can lose a production schema to a mis-typed prefix");
        }
    }

    [TestCaseSource(nameof(Dialects))]
    public void NoBatchSeparatorSurvivesIntoTheScript(string dialect)
    {
        string[] lines = Lines(GeneratedScript(dialect));

        lines.Should().NotContain(line => line.Trim().Equals("GO", StringComparison.OrdinalIgnoreCase),
            "GO is sqlcmd's rather than T-SQL's, and a provider rejects it");
        lines.Should().NotContain(line => line.Trim() == "/",
            "a lone slash is SQL*Plus's statement terminator and ODP.NET does not know it");
        lines.Should().NotContain(line => line.TrimStart().StartsWith("SET TERM", StringComparison.OrdinalIgnoreCase),
            "SET TERM is an isql directive; the Firebird provider takes one statement per command");
    }

    [TestCaseSource(nameof(Dialects))]
    public void TheHeaderIsTheOnlyChunkWithNoStatementInIt(string dialect)
    {
        string[] chunks = Chunks(GeneratedScript(dialect));

        chunks.Should().HaveCountGreaterThan(12,
            "twelve tables at least, so a split that produced fewer means the separator moved and the "
            + "whole file would go to the provider as one command");

        HasStatement(chunks[0]).Should().BeFalse(
            "the header explains the file rather than doing anything, and the job store skips it");

        chunks.Skip(1).Should().AllSatisfy(chunk => HasStatement(chunk).Should().BeTrue(
            "a chunk of nothing but comments anywhere after the header means an object went missing:"
            + Environment.NewLine + chunk));
    }

    // ---------------------------------------------------------------------------------------------
    // Reading the two kinds of script
    // ---------------------------------------------------------------------------------------------

    private static string GeneratedScript(string dialect)
    {
        string name = $"Quartz.Impl.AdoJobStore.Schema.create_{dialect}.sql";

        using Stream stream = typeof(IScheduler).Assembly.GetManifestResourceStream(name)
            ?? throw new InvalidOperationException(
                $"'{name}' is not embedded in Quartz.dll. Run 'dotnet fallout GenerateSchema'.");

        using StreamReader reader = new(stream, Encoding.UTF8);
        return reader.ReadToEnd();
    }

    private static string FreshInstallScript(string dialect)
    {
        string path = Path.Combine(RepositoryRoot.Find().FullName, "database", "tables", $"tables_{dialect}.sql");
        return File.ReadAllText(path);
    }

    private static string[] Lines(string script) => script.Replace("\r\n", "\n").Split('\n');

    private static string[] Chunks(string script) =>
        script.Replace("\r\n", "\n").Split($"\n{StatementSeparator}\n");

    private static IEnumerable<string> Statements(string script) => Chunks(script).Where(HasStatement);

    /// <summary>Whether a chunk holds anything but blank lines and whole-line comments.</summary>
    private static bool HasStatement(string chunk) =>
        Lines(chunk).Any(line => line.Trim().Length > 0 && !line.TrimStart().StartsWith("--", StringComparison.Ordinal));

    // ---------------------------------------------------------------------------------------------
    // The parser
    // ---------------------------------------------------------------------------------------------

    /// <summary>
    /// The table, column, index and trigger names one script declares, with the prefix normalized
    /// away so a generated script and a fresh-install one compare directly.
    /// </summary>
    private sealed record SqlObjects(
        Dictionary<string, List<string>> Tables,
        List<string> Indexes,
        List<string> Triggers)
    {
        private static readonly Regex CreateTable = new(
            @"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:\[?DBO\]?\.)?\[?(?<name>[\w.]+?)\]?\s*\(",
            RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);

        // MySQL declares its indexes inside CREATE TABLE, which is the one shape difference between
        // the two kinds of script; matching both spellings is what lets one comparison serve both.
        private static readonly Regex CreateIndex = new(
            @"(?:CREATE\s+INDEX\s+(?:IF\s+NOT\s+EXISTS\s+)?|^\s*KEY\s+)\[?(?<name>\w+)\]?\s*[(\s]",
            RegexOptions.IgnoreCase | RegexOptions.CultureInvariant | RegexOptions.Multiline);

        private static readonly Regex CreateTrigger = new(
            @"CREATE\s+TRIGGER\s+(?:IF\s+NOT\s+EXISTS\s+)?\[?(?<name>\w+)\]?",
            RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);

        /// <summary>A column item: a bare identifier followed by a type, and not a constraint clause.</summary>
        private static readonly Regex ColumnItem = new(
            @"^\[?(?<name>[A-Za-z_]\w*)\]?\s+[A-Za-z]",
            RegexOptions.CultureInvariant);

        private static readonly string[] NotColumns =
            ["PRIMARY", "FOREIGN", "CONSTRAINT", "REFERENCES", "KEY", "UNIQUE", "INDEX"];

        public static SqlObjects Parse(string script)
        {
            string normalized = Normalize(script);

            Dictionary<string, List<string>> tables = new(StringComparer.Ordinal);
            foreach (Match match in CreateTable.Matches(normalized))
            {
                tables[Unprefixed(match.Groups["name"].Value)] = Columns(Body(normalized, match.Index + match.Length));
            }

            return new SqlObjects(tables, Names(CreateIndex, normalized), Names(CreateTrigger, normalized));
        }

        private static List<string> Names(Regex declaration, string script) => declaration.Matches(script)
            .Select(m => Unprefixed(m.Groups["name"].Value))
            .Distinct(StringComparer.Ordinal)
            .Order(StringComparer.Ordinal)
            .ToList();

        /// <summary>
        /// Puts both kinds of script into one vocabulary: comments go, since prose about a CREATE
        /// INDEX is not one; the placeholders become the default prefix; and the case difference
        /// between the dialects whose script is written lowercase and the ones whose is not stops
        /// mattering.
        /// </summary>
        private static string Normalize(string script)
        {
            IEnumerable<string> lines = script
                .Replace("\r\n", "\n")
                .Split('\n')
                .Where(line => !line.TrimStart().StartsWith("#", StringComparison.Ordinal))
                .Select(StripTrailingComment);

            return string.Join('\n', lines)
                .Replace("{0}", "QRTZ_", StringComparison.Ordinal)
                .Replace("{1}", "QRTZ_", StringComparison.Ordinal)
                .ToUpperInvariant();
        }

        /// <summary>
        /// Drops a <c>--</c> comment. No script has a string literal holding one, so the first
        /// occurrence on a line always starts a comment.
        /// </summary>
        private static string StripTrailingComment(string line)
        {
            int comment = line.IndexOf("--", StringComparison.Ordinal);
            return comment >= 0 ? line[..comment] : line;
        }

        /// <summary>
        /// Everything Quartz creates carries the prefix, and an index or constraint name carries it in
        /// the middle — <c>IDX_QRTZ_T_J</c> — so it comes off wherever it sits.
        /// </summary>
        private static string Unprefixed(string name) => name.Replace("QRTZ_", "", StringComparison.Ordinal);

        /// <summary>The text between a <c>CREATE TABLE ... (</c> and its matching close paren.</summary>
        private static string Body(string script, int start)
        {
            int depth = 1;
            for (int i = start; i < script.Length; i++)
            {
                depth += script[i] switch { '(' => 1, ')' => -1, _ => 0 };
                if (depth == 0)
                {
                    return script[start..i];
                }
            }

            throw new InvalidOperationException("Unbalanced parentheses in a CREATE TABLE body.");
        }

        private static List<string> Columns(string body)
        {
            List<string> columns = [];
            int depth = 0;
            StringBuilder item = new();

            // Split on the commas separating the body's own items rather than on every comma: a type's
            // precision and a key's column list each hold commas of their own.
            foreach (char c in body + ",")
            {
                depth += c switch { '(' => 1, ')' => -1, _ => 0 };

                if (c == ',' && depth == 0)
                {
                    Add(columns, item.ToString());
                    item.Clear();
                    continue;
                }

                item.Append(c);
            }

            columns.Sort(StringComparer.Ordinal);
            return columns;
        }

        private static void Add(List<string> columns, string item)
        {
            string trimmed = item.Replace('\n', ' ').Replace('\t', ' ').Trim();

            Match match = ColumnItem.Match(trimmed);
            if (match.Success && !NotColumns.Contains(match.Groups["name"].Value, StringComparer.Ordinal))
            {
                columns.Add(match.Groups["name"].Value);
            }
        }
    }
}
