<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Quartz.NET ASP.NET Core integration; $(Description)</Description>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Quartz</RootNamespace>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <Authors>Lewis Zou, Marko Lahma, Quartz.NET</Authors>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Quartz\Quartz.csproj" />
  </ItemGroup>

</Project>
