<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html>

<head>
	<meta http-equiv="content-type" content="text/html; charset=iso-8859-1">
	<meta name="description" content="Quartz.NET is a port of Java Quartz which is an enterprise class job sheduling system. Quartz.NET is a free open source tool that you can use in your .NET applications.">
	<meta name="keywords" content="Quartz.NET Quartz Scheduler Scheduling .NET C# cron timer free download open source">
	<meta name="author" content="Marko Lahma">
	<link rel="stylesheet" type="text/css" href="default.css" media="screen">
	<title>Quartz.NET - Enterprise Job Scheduler for .NET Platform</title>
</head>

<body>

<div class="container">

	<div class="header">
		
		
		<div class="title">
			<h1>Quartz.NET - Enterprise Job Scheduler</h1>
		</div>
		
		<!--
		<div class="navigation">
			<a href="index.html">Vestibulum</a>
			<a href="index.html">Suspendisse</a>
			<a href="index.html">Elemen</a>
			<a href="index.html">Maecenas</a>
			<a href="index.html">Sodales</a>
			<div class="clearer"><span></span></div>
		</div>
		-->
	</div>

	<div class="main">
		
		<div class="content">

			$content$
			
		</div>

		<div class="sidenav">

			<!--
			<h1>Search</h1>
			<form action="index.html">
			<div>
				<input type="text" name="search" class="styled" /> <input type="submit" value="submit" class="button" />
			</div>
			</form>
			-->
 
			<h1>Quartz.NET</h1>
			<ul>
				<li><a href="index.html">Home</a></li>
				<li><a href="features.html">Features</a></li>
				<li><a href="download.html">Download</a></li>
				<li><a href="license.html">License</a></li>
				<li><a href="tutorial.html">Tutorial</a></li>
				<li><a href="faq.html">FAQ</a></li>
				<li><a href="apidoc/">API Documentation</a></li>
				<li><a href="mailing_list.html">Mailing List</a></li>
			</ul>

			<h1>Related</h1>
			<ul>
				<li><a href="http://sourceforge.net/projects/quartznet">Source Forge Project</a></li>
				<li><a href="http://fisheye3.cenqua.com/browse/quartznet">FishEye Source Code Browsing</a></li>
				<li><a href="http://jira.opensymphony.com/browse/QRTZNET">JIRA Issue Tracking</a></li>
				<li><a href="http://www.opensymphony.com/quartz/">Quartz (Java)</a></li>
			</ul>

			<h1>Project Supporters</h1>
			<p align="center">
				<a href="http://www.cenqua.com"><img src="http://www.cenqua.com/images/cenquad1.gif" width="89" height="33" border="0" alt="Supported by Cenqua"/></a> 
				<br />
				<br />
				<a href="http://www.innovasys.com"><img src="img/innovasys.gif" border="0" alt="Supported by Innovasys"/></a> 
				<br />
				<br />
				<a href="http://sourceforge.net"><img src="http://sflogo.sourceforge.net/sflogo.php?group_id=174134&amp;type=1" width="88" height="31" border="0" alt="SourceForge.net Logo" /></a>
			</p>

			
			<p align="right">
			</p>
		</div>
	
		<div class="clearer"><span></span></div>

	</div>

</div>

<div class="footer">
	Template design by <a href="http://arcsin.se">Arcsin</a>
</div>
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-1433901-1";
urchinTracker();
</script>
</body>

</html>