-- Quartz.NET schema migration: add PREFERRED_NODE and PREFERRED_NODE_AUTO columns
-- Supports preferred node feature (node affinity / job pinning in clusters)
-- This migration is optional. Without it, preferred node functionality is not available.
--
-- Both columns must be added together: PREFERRED_NODE holds the node name verbatim (or the
-- "*" sentinel requesting auto-pin), while PREFERRED_NODE_AUTO records whether that pin was
-- claimed automatically by the node that first fired the trigger. Quartz probes for both and
-- only enables node affinity when both are present.

-- SQL Server
-- ALTER TABLE QRTZ_TRIGGERS ADD PREFERRED_NODE NVARCHAR(200) NULL;
-- ALTER TABLE QRTZ_TRIGGERS ADD PREFERRED_NODE_AUTO BIT NOT NULL DEFAULT 0;

-- PostgreSQL
-- ALTER TABLE QRTZ_TRIGGERS ADD COLUMN PREFERRED_NODE VARCHAR(200) NULL;
-- ALTER TABLE QRTZ_TRIGGERS ADD COLUMN PREFERRED_NODE_AUTO BOOL NOT NULL DEFAULT FALSE;

-- MySQL
-- ALTER TABLE QRTZ_TRIGGERS ADD COLUMN PREFERRED_NODE VARCHAR(200) NULL;
-- ALTER TABLE QRTZ_TRIGGERS ADD COLUMN PREFERRED_NODE_AUTO BOOLEAN NOT NULL DEFAULT FALSE;

-- Oracle
-- ALTER TABLE QRTZ_TRIGGERS ADD (PREFERRED_NODE VARCHAR2(200) NULL);
-- ALTER TABLE QRTZ_TRIGGERS ADD (PREFERRED_NODE_AUTO VARCHAR2(1) DEFAULT '0' NOT NULL);

-- SQLite
-- ALTER TABLE QRTZ_TRIGGERS ADD COLUMN PREFERRED_NODE VARCHAR(200) NULL;
-- ALTER TABLE QRTZ_TRIGGERS ADD COLUMN PREFERRED_NODE_AUTO BIT NOT NULL DEFAULT 0;

-- Firebird
-- ALTER TABLE QRTZ_TRIGGERS ADD PREFERRED_NODE VARCHAR(200);
-- ALTER TABLE QRTZ_TRIGGERS ADD PREFERRED_NODE_AUTO SMALLINT DEFAULT 0 NOT NULL;
