/*
Convert the IMAGE data types to VARBINARY(MAX)
Upgrade SQL Server database from 22 to 23?
*/

--USE [database_name];
--GO

ALTER TABLE [dbo].[QRTZ_CALENDARS]
ALTER COLUMN [CALENDAR] [VARBINARY](MAX) NOT NULL;
GO

ALTER TABLE [dbo].[QRTZ_JOB_DETAILS]
ALTER COLUMN [JOB_DATA] [VARBINARY](MAX) NULL;
GO

ALTER TABLE [dbo].[QRTZ_BLOB_TRIGGERS]
ALTER COLUMN [BLOB_DATA] [VARBINARY](MAX) NULL;
GO

ALTER TABLE [dbo].[QRTZ_TRIGGERS]
ALTER COLUMN [JOB_DATA] [VARBINARY](MAX) NULL;
GO