#region License

/*
 * All content copyright Marko Lahma, unless otherwise indicated. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 */

#endregion

using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis.CSharp;

namespace Quartz.Analyzers;

/// <summary>
/// Writes the registration the declared jobs add up to.
/// </summary>
/// <remarks>
/// <para>
/// What comes out is the code an application would have written by hand: the same
/// <c>AddJob&lt;T&gt;</c>, the same <c>AddTrigger&lt;T&gt;</c>, the same builder chain. A reader who
/// opens the generated file should recognise their own registration in it, and a call that is not in
/// the attributes is not in the file — a default is left off rather than spelled out, so what is
/// written is what was asked for.
/// </para>
/// <para>
/// The class is in the <c>Quartz</c> namespace so that <c>AddDeclaredJobs</c> is reached by the
/// <c>using Quartz;</c> the surrounding <c>AddQuartz</c> call already needs, and internal so that two
/// assemblies declaring jobs do not collide. Where <c>InternalsVisibleTo</c> would make them collide
/// anyway, <see cref="RegistrationName" /> is what renames this one.
/// </para>
/// </remarks>
internal static class DeclaredJobsEmitter
{
    private const string TimeZonesTypeName = "global::Quartz.TimeZones";

    private const string CronMisfireInstructionTypeName = "global::Quartz.CronTriggerMisfireInstruction";

    private const string SimpleMisfireInstructionTypeName = "global::Quartz.SimpleTriggerMisfireInstruction";

    private const string ConfigurationTypeName = "global::Microsoft.Extensions.Configuration.IConfiguration";

    private const string TimeSpanTypeName = "global::System.TimeSpan";

    /// <summary>
    /// The generated helper a <c>[CronTrigger]</c> with a <c>ConfigurationKey</c> reads its expression
    /// through.
    /// </summary>
    private const string ConfiguredCronExpressionName = "ConfiguredCronExpression";

    /// <summary>
    /// The generated helper a <c>[SimpleTrigger]</c> with a <c>ConfigurationKey</c> reads its interval
    /// through.
    /// </summary>
    private const string ConfiguredIntervalName = "ConfiguredInterval";

    /// <summary>
    /// Where a statement in the method body starts: namespace, class and method each indent once.
    /// </summary>
    private const string BodyIndent = "            ";

    /// <summary>
    /// The whole generated file.
    /// </summary>
    /// <remarks>
    /// The file is compiled as part of whatever project it is generated into, so it is written in the
    /// C# the oldest of them reads: C# 8, whose <c>#nullable</c> is the newest thing in it. That is why
    /// the namespace is a block rather than file-scoped, which would need C# 10.
    /// </remarks>
    internal static string Emit(IReadOnlyList<DeclaredJob> jobs, RegistrationName registration)
    {
        StringBuilder source = new StringBuilder();

        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine("namespace Quartz");
        source.AppendLine("{");
        source.AppendLine("    /// <summary>");
        source.AppendLine("    /// The jobs this assembly declares with <c>[QuartzJob]</c>, as the calls that register them.");
        source.AppendLine("    /// </summary>");
        source.AppendLine("    /// <remarks>");
        source.AppendLine("    /// Written by Quartz's source generator from the attributes on the job classes. Every call below");
        source.AppendLine("    /// is one this application could have written by hand, and means there what it means here.");

        if (registration.VisibleAssembly is not null)
        {
            source.AppendLine("    /// Named after this assembly because another assembly's <c>QuartzDeclaredJobs</c> is visible here");
            source.AppendLine("    /// through <c>InternalsVisibleTo</c>, and <c>AddDeclaredJobs()</c> here means that assembly's jobs.");
        }

        source.AppendLine("    /// </remarks>");
        source.AppendLine($"    internal static class {registration.ClassName}");
        source.AppendLine("    {");
        source.AppendLine("        /// <summary>");
        source.AppendLine("        /// Adds every job this assembly declares, and every schedule those jobs declare.");
        source.AppendLine("        /// </summary>");
        source.AppendLine("        /// <param name=\"builder\">The scheduler being built.</param>");
        source.AppendLine("        /// <returns>The same builder, so that the call chains.</returns>");

        string bodyMethod = registration.HasOrdinaryMethod ? RegistrationName.OrdinaryMethodName : registration.AssemblyMethodName;
        source.AppendLine($"        public static global::Quartz.IQuartzBuilder {bodyMethod}(this global::Quartz.IQuartzBuilder builder)");
        source.AppendLine("        {");

        bool first = true;

        foreach (DeclaredJob job in jobs)
        {
            if (!first)
            {
                source.AppendLine();
            }

            first = false;
            AppendJob(source, job);
        }

        source.AppendLine();
        source.Append(BodyIndent).AppendLine("return builder;");
        source.AppendLine("        }");

        if (registration.HasOrdinaryMethod)
        {
            AppendAssemblyMethod(source, registration.AssemblyMethodName);
        }

        if (jobs.Any(x => x.Triggers.Any(y => y.ConfigurationKey is not null && y.Schedule is DeclaredCronSchedule)))
        {
            AppendConfiguredCronExpression(source);
        }

        if (jobs.Any(x => x.Triggers.Any(y => y.ConfigurationKey is not null && y.Schedule is DeclaredSimpleSchedule)))
        {
            AppendConfiguredInterval(source);
        }

        source.AppendLine("    }");
        source.AppendLine("}");

        return source.ToString();
    }

    /// <summary>
    /// The same registration under this assembly's own name, which no other assembly's can share.
    /// </summary>
    /// <remarks>
    /// Two libraries granting one application <c>InternalsVisibleTo</c> make <c>AddDeclaredJobs()</c>
    /// ambiguous there; each library's own name still binds. It calls the ordinary method by its simple
    /// name, which the class's own member answers before any extension could.
    /// </remarks>
    private static void AppendAssemblyMethod(StringBuilder source, string methodName)
    {
        source.AppendLine();
        source.AppendLine("        /// <summary>");
        source.AppendLine("        /// The same as <c>AddDeclaredJobs</c>, under a name no other assembly's registration shares, so");
        source.AppendLine("        /// that it binds wherever this assembly's is visible, however many others are visible beside it.");
        source.AppendLine("        /// </summary>");
        source.AppendLine("        /// <param name=\"builder\">The scheduler being built.</param>");
        source.AppendLine("        /// <returns>The same builder, so that the call chains.</returns>");
        source.AppendLine($"        public static global::Quartz.IQuartzBuilder {methodName}(this global::Quartz.IQuartzBuilder builder)");
        source.AppendLine("        {");
        source.Append(BodyIndent).AppendLine($"return {RegistrationName.OrdinaryMethodName}(builder);");
        source.AppendLine("        }");
    }

    /// <summary>
    /// The read a <c>ConfigurationKey</c> turns into, written once and called by every trigger that has one.
    /// </summary>
    /// <remarks>
    /// <c>GetService(Type)</c> rather than the generic extension, so the file names only
    /// <c>IConfiguration</c>, which is exactly what the generator checks the compilation for. Nothing here
    /// reflects: it is the lookup a hand-written <c>(services, trigger) =&gt;</c> registration would make.
    /// </remarks>
    private static void AppendConfiguredCronExpression(StringBuilder source)
    {
        source.AppendLine();
        source.AppendLine("        /// <summary>");
        source.AppendLine("        /// The cron expression configured at <paramref name=\"key\" />, or <paramref name=\"declared\" />,");
        source.AppendLine("        /// the attribute's own, where the key is not set or no configuration is registered.");
        source.AppendLine("        /// </summary>");
        source.AppendLine("        /// <param name=\"services\">The scheduler's view of the container.</param>");
        source.AppendLine("        /// <param name=\"key\">The attribute's <c>ConfigurationKey</c>.</param>");
        source.AppendLine("        /// <param name=\"declared\">The attribute's cron expression.</param>");
        source.AppendLine("        /// <returns>The expression the trigger fires on.</returns>");
        source.AppendLine($"        private static string {ConfiguredCronExpressionName}(global::System.IServiceProvider services, string key, string declared)");
        source.AppendLine("        {");
        source.Append(BodyIndent).AppendLine($"{ConfigurationTypeName}? configuration =");
        source.Append(BodyIndent).AppendLine($"    services.GetService(typeof({ConfigurationTypeName})) as {ConfigurationTypeName};");
        source.AppendLine();
        source.Append(BodyIndent).AppendLine("return configuration?[key] ?? declared;");
        source.AppendLine("        }");
    }

    /// <summary>
    /// The read a <c>[SimpleTrigger]</c>'s <c>ConfigurationKey</c> turns into, written once and called by
    /// every interval that has one.
    /// </summary>
    /// <remarks>
    /// The configured string is parsed as the attribute's is, invariantly, and a value that is not a
    /// positive interval throws while the scheduler is built, naming the key: the configured schedule is
    /// then one the host refuses to start with rather than one that never fires.
    /// </remarks>
    private static void AppendConfiguredInterval(StringBuilder source)
    {
        source.AppendLine();
        source.AppendLine("        /// <summary>");
        source.AppendLine("        /// The interval configured at <paramref name=\"key\" />, or <paramref name=\"declared\" />, the");
        source.AppendLine("        /// attribute's own, where the key is not set or no configuration is registered.");
        source.AppendLine("        /// </summary>");
        source.AppendLine("        /// <param name=\"services\">The scheduler's view of the container.</param>");
        source.AppendLine("        /// <param name=\"key\">The attribute's <c>ConfigurationKey</c>.</param>");
        source.AppendLine("        /// <param name=\"declared\">The attribute's interval.</param>");
        source.AppendLine("        /// <returns>The interval the trigger fires on.</returns>");
        source.AppendLine("        /// <exception cref=\"global::System.FormatException\">The configured value is not a positive invariant <c>TimeSpan</c>.</exception>");
        source.AppendLine($"        private static {TimeSpanTypeName} {ConfiguredIntervalName}(global::System.IServiceProvider services, string key, {TimeSpanTypeName} declared)");
        source.AppendLine("        {");
        source.Append(BodyIndent).AppendLine($"{ConfigurationTypeName}? configuration =");
        source.Append(BodyIndent).AppendLine($"    services.GetService(typeof({ConfigurationTypeName})) as {ConfigurationTypeName};");
        source.AppendLine();
        source.Append(BodyIndent).AppendLine("string? configured = configuration?[key];");
        source.Append(BodyIndent).AppendLine("if (configured is null)");
        source.Append(BodyIndent).AppendLine("{");
        source.Append(BodyIndent).AppendLine("    return declared;");
        source.Append(BodyIndent).AppendLine("}");
        source.AppendLine();
        source.Append(BodyIndent).AppendLine($"{TimeSpanTypeName} interval;");
        source.Append(BodyIndent).AppendLine($"if (!{TimeSpanTypeName}.TryParse(configured, global::System.Globalization.CultureInfo.InvariantCulture, out interval) || interval <= {TimeSpanTypeName}.Zero)");
        source.Append(BodyIndent).AppendLine("{");
        source.Append(BodyIndent).AppendLine("    throw new global::System.FormatException(");
        source.Append(BodyIndent).AppendLine("        \"The configuration key '\" + key + \"' holds '\" + configured + \"', which is not a positive TimeSpan. \"");
        source.Append(BodyIndent).AppendLine("        + \"Spell the trigger's interval the way TimeSpan does, invariantly: \\\"00:10:00\\\" for ten minutes, \\\"1.00:00:00\\\" for a day.\");");
        source.Append(BodyIndent).AppendLine("}");
        source.AppendLine();
        source.Append(BodyIndent).AppendLine("return interval;");
        source.AppendLine("        }");
    }

    private static void AppendJob(StringBuilder source, DeclaredJob job)
    {
        string indent = BodyIndent;

        if (job.Scheduler is not null)
        {
            source.Append(indent).AppendLine($"// {job.DisplayName} belongs to the {Literal(job.Scheduler)} scheduler alone.");
            source.Append(indent).AppendLine($"if (builder.SchedulerName == {Literal(job.Scheduler)})");
            source.Append(indent).AppendLine("{");
            indent += "    ";
        }

        AppendLines(source, indent, JobLines(job));

        foreach (DeclaredTrigger trigger in job.Triggers)
        {
            source.AppendLine();
            AppendLines(source, indent, TriggerLines(job, trigger));
        }

        if (job.Scheduler is not null)
        {
            source.Append(BodyIndent).AppendLine("}");
        }
    }

    private static List<string> JobLines(DeclaredJob job)
    {
        List<string> lines =
        [
            $"builder.AddJob<{job.TypeName}>(job => job",
            "    " + Identity(job.Name, job.Group),
        ];

        if (job.Description is not null)
        {
            lines.Add($"    .WithDescription({Literal(job.Description)})");
        }

        if (job.Durable)
        {
            lines.Add("    .StoreDurably(true)");
        }

        if (job.RequestRecovery)
        {
            lines.Add("    .RequestRecovery(true)");
        }

        Close(lines, ");");
        return lines;
    }

    private static List<string> TriggerLines(DeclaredJob job, DeclaredTrigger trigger)
    {
        string forJob = job.Group is null
            ? $".ForJob({Literal(job.Name)})"
            : $".ForJob({Literal(job.Name)}, {Literal(job.Group)})";

        // A schedule read from configuration needs the container, which only the (services, trigger)
        // overload is handed; one that is the attribute's alone keeps the shorter call.
        string configurator = trigger.ConfigurationKey is null ? "trigger" : "(services, trigger)";

        List<string> lines =
        [
            $"builder.AddTrigger<{job.TypeName}>({configurator} => trigger",
            "    " + Identity(trigger.Name, trigger.Group),
            "    " + forJob,
        ];

        if (trigger.Priority != TriggerConstants.DefaultPriority)
        {
            lines.Add($"    .WithPriority({trigger.Priority.ToString(CultureInfo.InvariantCulture)})");
        }

        if (trigger.Description is not null)
        {
            lines.Add($"    .WithDescription({Literal(trigger.Description)})");
        }

        if (trigger.ExecutionGroup is not null)
        {
            lines.Add($"    .WithExecutionGroup({Literal(trigger.ExecutionGroup)})");
        }

        switch (trigger.Schedule)
        {
            case DeclaredCronSchedule cron:
                AppendCronSchedule(lines, trigger, cron);
                break;
            case DeclaredSimpleSchedule simple:
                AppendSimpleSchedule(lines, trigger, simple);
                break;
        }

        Close(lines, ");");
        return lines;
    }

    private static void AppendCronSchedule(List<string> lines, DeclaredTrigger trigger, DeclaredCronSchedule cron)
    {
        List<string> schedule = CronScheduleLines(trigger, cron);

        string expression = trigger.ConfigurationKey is null
            ? Literal(cron.CronExpression)
            : $"{ConfiguredCronExpressionName}(services, {Literal(trigger.ConfigurationKey)}, {Literal(cron.CronExpression)})";

        if (schedule.Count == 0)
        {
            lines.Add($"    .WithCronSchedule({expression})");
            return;
        }

        lines.Add($"    .WithCronSchedule({expression}, cron => cron");

        foreach (string line in schedule)
        {
            lines.Add("        " + line);
        }

        Close(lines, ")");
    }

    /// <summary>
    /// What the cron schedule needs beyond its expression, or nothing when it needs nothing — in
    /// which case no callback is emitted at all.
    /// </summary>
    private static List<string> CronScheduleLines(DeclaredTrigger trigger, DeclaredCronSchedule cron)
    {
        List<string> lines = [];

        if (cron.TimeZone is not null)
        {
            lines.Add($".InTimeZone({TimeZonesTypeName}.FindById({Literal(cron.TimeZone)}))");
        }

        AddMisfireInstruction(lines, trigger, CronMisfireInstructionTypeName);

        return lines;
    }

    /// <summary>
    /// The interval schedule, always as the callback: an interval and a repeat count are both said, so
    /// there is no shorter call that says as much.
    /// </summary>
    /// <remarks>
    /// The interval is written as the ticks this build read, with the attribute's value in its invariant
    /// form beside it for whoever reads the file; <c>-1</c> is written as the <c>RepeatForever()</c> a
    /// hand-written registration would call.
    /// </remarks>
    private static void AppendSimpleSchedule(List<string> lines, DeclaredTrigger trigger, DeclaredSimpleSchedule simple)
    {
        string declared = $"{TimeSpanTypeName}.FromTicks({simple.IntervalTicks.ToString(CultureInfo.InvariantCulture)})";

        string interval = trigger.ConfigurationKey is null
            ? declared
            : $"{ConfiguredIntervalName}(services, {Literal(trigger.ConfigurationKey)}, {declared})";

        List<string> schedule =
        [
            $".WithInterval({interval}) // {simple.IntervalText}",
            simple.RepeatCount == SimpleTriggerLiteralAnalyzer.RepeatIndefinitely
                ? ".RepeatForever()"
                : $".WithRepeatCount({simple.RepeatCount.ToString(CultureInfo.InvariantCulture)})",
        ];

        AddMisfireInstruction(schedule, trigger, SimpleMisfireInstructionTypeName);

        lines.Add("    .WithSimpleSchedule(simple => simple");

        foreach (string line in schedule)
        {
            lines.Add("        " + line);
        }

        Close(lines, ")");
    }

    private static void AddMisfireInstruction(List<string> lines, DeclaredTrigger trigger, string enumTypeName)
    {
        // Zero is SmartPolicy in both families, which is what a trigger does when nothing says otherwise.
        if (trigger.MisfireInstruction == 0)
        {
            return;
        }

        string instruction = trigger.MisfireInstructionName is null
            ? $"({enumTypeName}) {trigger.MisfireInstruction.ToString(CultureInfo.InvariantCulture)}"
            : $"{enumTypeName}.{trigger.MisfireInstructionName}";

        lines.Add($".WithMisfireInstruction({instruction})");
    }

    private static string Identity(string name, string? group)
        => group is null
            ? $".WithIdentity({Literal(name)})"
            : $".WithIdentity({Literal(name)}, {Literal(group)})";

    private static void Close(List<string> lines, string suffix)
    {
        lines[lines.Count - 1] += suffix;
    }

    private static void AppendLines(StringBuilder source, string indent, List<string> lines)
    {
        foreach (string line in lines)
        {
            source.Append(indent).AppendLine(line);
        }
    }

    /// <summary>
    /// The value as C# source spells it, escapes and quotes included.
    /// </summary>
    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, quote: true);
}
