#region License

/*
 * All content copyright Marko Lahma, unless otherwise indicated. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 */

#endregion

using System.Collections.Generic;
using System.Globalization;
using System.Text;

using Microsoft.CodeAnalysis.CSharp;

namespace Quartz.Analyzers;

/// <summary>
/// Writes the registration the declared jobs add up to.
/// </summary>
/// <remarks>
/// <para>
/// What comes out is the code an application would have written by hand: the same
/// <c>AddJob&lt;T&gt;</c>, the same <c>AddTrigger&lt;T&gt;</c>, the same builder chain. A reader who
/// opens the generated file should recognise their own registration in it, and a call that is not in
/// the attributes is not in the file — a default is left off rather than spelled out, so what is
/// written is what was asked for.
/// </para>
/// <para>
/// The class is in the <c>Quartz</c> namespace so that <c>AddDeclaredJobs</c> is reached by the
/// <c>using Quartz;</c> the surrounding <c>AddQuartz</c> call already needs, and internal so that two
/// assemblies declaring jobs do not collide.
/// </para>
/// </remarks>
internal static class DeclaredJobsEmitter
{
    private const string TimeZonesTypeName = "global::Quartz.TimeZones";

    private const string MisfireInstructionTypeName = "global::Quartz.CronTriggerMisfireInstruction";

    internal static string Emit(IReadOnlyList<DeclaredJob> jobs)
    {
        StringBuilder source = new StringBuilder();

        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine("namespace Quartz;");
        source.AppendLine();
        source.AppendLine("/// <summary>");
        source.AppendLine("/// The jobs this assembly declares with <c>[QuartzJob]</c>, as the calls that register them.");
        source.AppendLine("/// </summary>");
        source.AppendLine("/// <remarks>");
        source.AppendLine("/// Written by Quartz's source generator from the attributes on the job classes. Every call below");
        source.AppendLine("/// is one this application could have written by hand, and means there what it means here.");
        source.AppendLine("/// </remarks>");
        source.AppendLine("internal static class QuartzDeclaredJobs");
        source.AppendLine("{");
        source.AppendLine("    /// <summary>");
        source.AppendLine("    /// Adds every job this assembly declares, and every schedule those jobs declare.");
        source.AppendLine("    /// </summary>");
        source.AppendLine("    /// <param name=\"builder\">The scheduler being built.</param>");
        source.AppendLine("    /// <returns>The same builder, so that the call chains.</returns>");
        source.AppendLine("    public static global::Quartz.IQuartzBuilder AddDeclaredJobs(this global::Quartz.IQuartzBuilder builder)");
        source.AppendLine("    {");

        bool first = true;

        foreach (DeclaredJob job in jobs)
        {
            if (!first)
            {
                source.AppendLine();
            }

            first = false;
            AppendJob(source, job);
        }

        source.AppendLine();
        source.AppendLine("        return builder;");
        source.AppendLine("    }");
        source.AppendLine("}");

        return source.ToString();
    }

    private static void AppendJob(StringBuilder source, DeclaredJob job)
    {
        string indent = "        ";

        if (job.Scheduler is not null)
        {
            source.Append(indent).AppendLine($"// {job.DisplayName} belongs to the {Literal(job.Scheduler)} scheduler alone.");
            source.Append(indent).AppendLine($"if (builder.SchedulerName == {Literal(job.Scheduler)})");
            source.Append(indent).AppendLine("{");
            indent += "    ";
        }

        AppendLines(source, indent, JobLines(job));

        foreach (DeclaredTrigger trigger in job.Triggers)
        {
            source.AppendLine();
            AppendLines(source, indent, TriggerLines(job, trigger));
        }

        if (job.Scheduler is not null)
        {
            source.Append("        ").AppendLine("}");
        }
    }

    private static List<string> JobLines(DeclaredJob job)
    {
        List<string> lines =
        [
            $"builder.AddJob<{job.TypeName}>(job => job",
            "    " + Identity(job.Name, job.Group),
        ];

        if (job.Description is not null)
        {
            lines.Add($"    .WithDescription({Literal(job.Description)})");
        }

        if (job.Durable)
        {
            lines.Add("    .StoreDurably(true)");
        }

        if (job.RequestRecovery)
        {
            lines.Add("    .RequestRecovery(true)");
        }

        Close(lines, ");");
        return lines;
    }

    private static List<string> TriggerLines(DeclaredJob job, DeclaredTrigger trigger)
    {
        string forJob = job.Group is null
            ? $".ForJob({Literal(job.Name)})"
            : $".ForJob({Literal(job.Name)}, {Literal(job.Group)})";

        List<string> lines =
        [
            $"builder.AddTrigger<{job.TypeName}>(trigger => trigger",
            "    " + Identity(trigger.Name, trigger.Group),
            "    " + forJob,
        ];

        if (trigger.Priority != TriggerConstants.DefaultPriority)
        {
            lines.Add($"    .WithPriority({trigger.Priority.ToString(CultureInfo.InvariantCulture)})");
        }

        if (trigger.Description is not null)
        {
            lines.Add($"    .WithDescription({Literal(trigger.Description)})");
        }

        if (trigger.ExecutionGroup is not null)
        {
            lines.Add($"    .WithExecutionGroup({Literal(trigger.ExecutionGroup)})");
        }

        List<string> schedule = ScheduleLines(trigger);

        if (schedule.Count == 0)
        {
            lines.Add($"    .WithCronSchedule({Literal(trigger.CronExpression)})");
        }
        else
        {
            lines.Add($"    .WithCronSchedule({Literal(trigger.CronExpression)}, cron => cron");

            foreach (string line in schedule)
            {
                lines.Add("        " + line);
            }

            Close(lines, ")");
        }

        Close(lines, ");");
        return lines;
    }

    /// <summary>
    /// What the cron schedule needs beyond its expression, or nothing when it needs nothing — in
    /// which case no callback is emitted at all.
    /// </summary>
    private static List<string> ScheduleLines(DeclaredTrigger trigger)
    {
        List<string> lines = [];

        if (trigger.TimeZone is not null)
        {
            lines.Add($".InTimeZone({TimeZonesTypeName}.FindById({Literal(trigger.TimeZone)}))");
        }

        // Zero is SmartPolicy, which is what a trigger does when nothing says otherwise.
        if (trigger.MisfireInstruction != 0)
        {
            string instruction = trigger.MisfireInstructionName is null
                ? $"({MisfireInstructionTypeName}) {trigger.MisfireInstruction.ToString(CultureInfo.InvariantCulture)}"
                : $"{MisfireInstructionTypeName}.{trigger.MisfireInstructionName}";

            lines.Add($".WithMisfireInstruction({instruction})");
        }

        return lines;
    }

    private static string Identity(string name, string? group)
        => group is null
            ? $".WithIdentity({Literal(name)})"
            : $".WithIdentity({Literal(name)}, {Literal(group)})";

    private static void Close(List<string> lines, string suffix)
    {
        lines[lines.Count - 1] += suffix;
    }

    private static void AppendLines(StringBuilder source, string indent, List<string> lines)
    {
        foreach (string line in lines)
        {
            source.Append(indent).AppendLine(line);
        }
    }

    /// <summary>
    /// The value as C# source spells it, escapes and quotes included.
    /// </summary>
    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, quote: true);
}
