#region License

/*
 * All content copyright Marko Lahma, unless otherwise indicated. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 */

#endregion

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis.CSharp;

namespace Quartz.Analyzers;

/// <summary>
/// Writes the interceptors the delegate jobs of one compilation add up to.
/// </summary>
/// <remarks>
/// <para>
/// One method per member and handler type, carrying an <c>[InterceptsLocation]</c> for every call of
/// that shape, so two handlers of one delegate type share their binding. Each method casts the handler
/// to its type once, when the job is added, and passes the call on to the member it replaced with the
/// handler paired with a lambda that resolves the arguments and calls it.
/// </para>
/// <para>
/// C# 11 is what the file needs, for the two file-local types, and nothing newer is used; the rest is
/// C# 8, as <see cref="DeclaredJobsEmitter" /> is.
/// </para>
/// </remarks>
internal static class DelegateJobsEmitter
{
    private const string ExtensionsTypeName = "global::Quartz.QuartzBuilderExtensions";

    private const string ValueTaskTypeName = "global::System.Threading.Tasks.ValueTask";

    private const string AsValueTaskName = "AsValueTask";

    /// <summary>
    /// What a firing reports when a handler declared to return a <c>Task</c> returned <see langword="null" />.
    /// </summary>
    /// <remarks>
    /// <c>DelegateJobBinding.NullTaskMessage</c>, word for word, since the generated code cannot reach
    /// Quartz's internals; <c>CompiledDelegateJobBindingTest</c> fails if the two part.
    /// </remarks>
    internal const string NullTaskMessage =
        "The delegate job's handler returned null rather than a Task, so there is nothing to await. "
        + "Return a completed task instead, or make the handler async.";

    /// <summary>
    /// Where a statement in an interceptor starts: namespace, class and method each indent once.
    /// </summary>
    private const string BodyIndent = "            ";

    internal static string Emit(IEnumerable<DelegateJobCall> calls)
    {
        // By file and position, so that the generated file is the same however the compiler happened to
        // order the syntax trees, and so that each method is named after the first call it replaces.
        List<DelegateJobCall> ordered = calls
            .OrderBy(x => x.Location.FilePath, StringComparer.Ordinal)
            .ThenBy(x => x.Location.Position)
            .ToList();

        List<List<DelegateJobCall>> methods = [];
        Dictionary<(DelegateJobMember, string), List<DelegateJobCall>> byShape = [];

        foreach (DelegateJobCall call in ordered)
        {
            if (!byShape.TryGetValue((call.Member, call.DelegateType), out List<DelegateJobCall>? shared))
            {
                shared = [];
                byShape.Add((call.Member, call.DelegateType), shared);
                methods.Add(shared);
            }

            shared.Add(call);
        }

        StringBuilder source = new StringBuilder();

        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine("namespace System.Runtime.CompilerServices");
        source.AppendLine("{");
        source.AppendLine("    // File-local, as every generator that intercepts declares it, so that no two of them collide.");
        source.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        source.AppendLine("    file sealed class InterceptsLocationAttribute : global::System.Attribute");
        source.AppendLine("    {");
        source.AppendLine("        public InterceptsLocationAttribute(int version, string data)");
        source.AppendLine("        {");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("}");
        source.AppendLine();
        source.AppendLine($"namespace {DelegateJobsGenerator.InterceptorsNamespace}");
        source.AppendLine("{");
        source.AppendLine("    /// <summary>");
        source.AppendLine("    /// The delegate jobs this assembly adds, each bound when it was compiled.");
        source.AppendLine("    /// </summary>");
        source.AppendLine("    /// <remarks>");
        source.AppendLine("    /// Written by Quartz's source generator. Each method replaces the AddJob or ScheduleJob calls named");
        source.AppendLine("    /// above it with the same call, whose handler arrives with code that resolves its parameters and");
        source.AppendLine("    /// calls it, so a firing runs no reflection. Quartz checks the handler as it does without this file.");
        source.AppendLine("    /// </remarks>");
        source.AppendLine("    file static class DelegateJobInterceptors");
        source.AppendLine("    {");

        Dictionary<DelegateJobMember, int> counts = [];
        bool first = true;

        foreach (List<DelegateJobCall> shared in methods)
        {
            if (!first)
            {
                source.AppendLine();
            }

            first = false;

            DelegateJobMember member = shared[0].Member;
            counts.TryGetValue(member, out int index);
            counts[member] = index + 1;

            AppendInterceptor(source, shared, MethodName(member) + index.ToString(CultureInfo.InvariantCulture));
        }

        if (ordered.Any(x => x.Completion == HandlerCompletion.Task))
        {
            AppendAsValueTask(source);
        }

        source.AppendLine("    }");
        source.AppendLine("}");

        return source.ToString();
    }

    private static void AppendInterceptor(StringBuilder source, List<DelegateJobCall> calls, string methodName)
    {
        DelegateJobCall shape = calls[0];
        (string configuratorType, string configuratorName) = Configurator(shape.Member);

        foreach (DelegateJobCall call in calls)
        {
            source.AppendLine(
                $"        [global::System.Runtime.CompilerServices.InterceptsLocation({call.Location.Version.ToString(CultureInfo.InvariantCulture)}, {Literal(call.Location.Data)})] // {call.Location.DisplayLocation}");
        }

        source.AppendLine($"        internal static global::Quartz.IQuartzBuilder {methodName}(");
        source.AppendLine("            this global::Quartz.IQuartzBuilder builder,");
        source.AppendLine("            string name,");
        source.AppendLine("            global::System.Delegate handler,");
        source.AppendLine($"            {configuratorType} {configuratorName})");
        source.AppendLine("        {");
        source.Append(BodyIndent).AppendLine($"{shape.DelegateType} typed =");
        source.Append(BodyIndent).AppendLine($"    ({shape.DelegateType}) handler;");
        source.AppendLine();
        source.Append(BodyIndent).AppendLine($"return {ExtensionsTypeName}.{PublicName(shape.Member)}(");
        source.Append(BodyIndent).AppendLine("    builder,");
        source.Append(BodyIndent).AppendLine("    name,");
        source.Append(BodyIndent).AppendLine($"    {ExtensionsTypeName}.WithCompiledBinding(handler, (context, services, cancellationToken) =>");

        foreach (string line in InvokerBody(shape))
        {
            source.Append(BodyIndent).Append("        ").AppendLine(line);
        }

        source.Append(BodyIndent).AppendLine($"    {configuratorName});");
        source.AppendLine("        }");
    }

    /// <summary>
    /// The lambda's body, ending with the <c>),</c> that closes <c>WithCompiledBinding</c>.
    /// </summary>
    private static List<string> InvokerBody(DelegateJobCall shape)
    {
        List<string> call = Invocation(shape);

        switch (shape.Completion)
        {
            case HandlerCompletion.ValueTask:
                Close(call, "),");
                return call;
            case HandlerCompletion.Task:
                call[0] = AsValueTaskName + "(" + call[0];
                Close(call, ")),");
                return call;
            default:
                List<string> body = ["{"];
                Close(call, ";");
                body.AddRange(call.Select(x => "    " + x));
                body.Add($"    return default({ValueTaskTypeName});");
                body.Add("}),");
                return body;
        }
    }

    /// <summary>
    /// <c>typed(…)</c>, one argument to a line once there are any.
    /// </summary>
    private static List<string> Invocation(DelegateJobCall shape)
    {
        List<HandlerParameter> parameters = shape.Parameters.ToList();
        if (parameters.Count == 0)
        {
            return ["typed()"];
        }

        List<string> lines = ["typed("];
        for (int i = 0; i < parameters.Count; i++)
        {
            lines.Add("    " + Argument(parameters[i]) + (i == parameters.Count - 1 ? ")" : ","));
        }

        return lines;
    }

    /// <summary>
    /// Where one argument comes from, as <c>DelegateJobBinding</c> reads it at run time: the non-generic
    /// <c>GetRequiredService</c> is the call it makes, so a missing service fails with the same message.
    /// </summary>
    private static string Argument(HandlerParameter parameter) => parameter.Source switch
    {
        ArgumentSource.Context => "context",
        ArgumentSource.CancellationToken => "cancellationToken",
        ArgumentSource.Services => "services",
        _ => $"({parameter.TypeName}) global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(services, typeof({parameter.TypeName}))",
    };

    private static void AppendAsValueTask(StringBuilder source)
    {
        source.AppendLine();
        source.AppendLine("        /// <summary>");
        source.AppendLine("        /// The task a handler returned, as the scheduler awaits it; a null one is refused as Quartz refuses it.");
        source.AppendLine("        /// </summary>");
        source.AppendLine($"        private static {ValueTaskTypeName} {AsValueTaskName}(global::System.Threading.Tasks.Task? task)");
        source.AppendLine("        {");
        source.Append(BodyIndent).AppendLine("if (task is null)");
        source.Append(BodyIndent).AppendLine("{");
        source.Append(BodyIndent).AppendLine($"    throw new global::System.InvalidOperationException({Literal(NullTaskMessage)});");
        source.Append(BodyIndent).AppendLine("}");
        source.AppendLine();
        source.Append(BodyIndent).AppendLine($"return new {ValueTaskTypeName}(task);");
        source.AppendLine("        }");
    }

    private static (string Type, string Name) Configurator(DelegateJobMember member) => member switch
    {
        DelegateJobMember.AddJob => ("global::System.Action<global::Quartz.IJobConfigurator<global::Quartz.IJob>>?", "configure"),
        DelegateJobMember.AddJobWithServices => ("global::System.Action<global::System.IServiceProvider, global::Quartz.IJobConfigurator<global::Quartz.IJob>>", "configure"),
        DelegateJobMember.ScheduleJob => ("global::System.Action<global::Quartz.ITriggerConfigurator<global::Quartz.IJob>>", "trigger"),
        _ => ("global::System.Action<global::System.IServiceProvider, global::Quartz.ITriggerConfigurator<global::Quartz.IJob>>", "trigger"),
    };

    private static string PublicName(DelegateJobMember member)
        => member is DelegateJobMember.AddJob or DelegateJobMember.AddJobWithServices ? "AddJob" : "ScheduleJob";

    /// <summary>
    /// The interceptor's name: the member it replaces, and whether that member takes the container.
    /// </summary>
    private static string MethodName(DelegateJobMember member) => member switch
    {
        DelegateJobMember.AddJob => "AddJob",
        DelegateJobMember.AddJobWithServices => "AddJobWithServices",
        DelegateJobMember.ScheduleJob => "ScheduleJob",
        _ => "ScheduleJobWithServices",
    };

    private static void Close(List<string> lines, string suffix)
    {
        lines[lines.Count - 1] += suffix;
    }

    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, quote: true);
}
