FROM microsoft/mssql-server-linux

ENV SA_PASSWORD Quartz!DockerP4ss
ENV ACCEPT_EULA Y 

# RUN apt-get update \
#     && apt-get install -y curl apt-transport-https \
#     && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
#     && curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | tee /etc/apt/sources.list.d/msprod.list \
#     && apt-get update \
#     && apt-get install -y mssql-tools unixodbc-dev
