name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
    - docs/**/*
    - package.json
    - docs.yml

  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - 'readme.md'

jobs:
  build_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    name: Build & Test
  
    steps:

    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Setup dotnet 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.*

    - name: Setup dotnet 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.*

    - name: Setup dotnet 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*

    - name: Build
      if: matrix.os == 'ubuntu-latest'
      run: |
        chmod u+x build.sh
        ./build.sh

    - name: Build
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        ./build.cmd
        
    - name: Unit Tests
      if: matrix.os == 'ubuntu-latest'
      run: |
        dotnet test -c Release --no-restore --no-build --framework net5.0 ./src/Quartz.Tests.Unit/Quartz.Tests.Unit.csproj 

    - name: Unit Tests
      if: matrix.os == 'windows-latest'
      run: |
        dotnet test -c Release --no-restore --no-build ./src/Quartz.Tests.Unit/Quartz.Tests.Unit.csproj 

#    - name: Integration Tests
#      run: |
#        dotnet test -c Release --no-restore --no-build ./src/Quartz.Tests.Integration/Quartz.Tests.Integration.csproj 
