name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
    - docs/**/*
    - package.json
    - docs.yml

  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - 'readme.md'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Setup dotnet 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.*
    - name: Setup dotnet 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.*
    - name: Setup dotnet 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*

    - name: Test
      run: dotnet test --configuration Release
