name: docs
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'package.json'
      - 'package-lock.json'
      - '**/docs*.yml'
jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build
        run: |
          npm install
          npm run docs:build

      - name: Deploy
        working-directory: ./docs/.vuepress/dist
        run: |
          git init .
          git config --global user.name "Quartz.NET"
          git config --global user.email "quartznet@quartz-scheduler.net"
          git fetch https://github.com/quartznet/quartznet.github.io.git
          git checkout 9966bc53c0685311bc9199498ef2338629f6ec4d
          git checkout -b master
          git add .
          git commit -am "Deploy Documentation"
          git push --force --set-upstream https://${{secrets.DOC_DEPLOY_KEY}}:x-oauth-basic@github.com/quartznet/quartznet.github.io.git master
